### ISSUE TITLE
Lambda Event Source Mapping

### ISSUE THREAD

**Issue by svenlito** [terraform-aws-modules/terraform-aws-lambda#102]
I know this isn't available yet, but was wondering if you have an API for this in mind. I could potentially work on this.

**Comment by antonbabenko** [comment]
I don't have anything in mind, so please feel free to work on this. I will be glad to review it when necessary.

**Comment by svenlito** [comment]
@antonbabenko first draft, please let me know if you think things could be improved further.

**Comment by antonbabenko** [comment]
[v1.37.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.37.0) has been just released.
