### ISSUE TITLE
Build lambda only based on hash

### ISSUE THREAD

**Issue by kromol** [terraform-aws-modules/terraform-aws-lambda#105]
Hello,

Using this module in CI pipeline causes re-deploying lambda function even though nothing has changed. It is due to the `timestamp`. I am wondering if using only the filename that is generated based on the content would be sufficient? If so, I could work on a PR to update it.

**Comment by antonbabenko** [comment]
Hi,

Please see the solution in the [FAQ section](https://github.com/terraform-aws-modules/terraform-aws-lambda#faq) in the README:

> Q3: null_resource.archive[0] must be replaced

> Answer: This probably mean that zip-archive has been deployed, but is currently absent locally, and it has to be recreated locally. When you run into this issue during CI/CD process (where workspace is clean), you can set environment variable TF_RECREATE_MISSING_LAMBDA_PACKAGE=false and run terraform apply.

See also #63

**Comment by minokyo** [comment]
I'm still seeing the Terraform in CI triggering change despite having following set:
```
TF_RECREATE_MISSING_LAMBDA_PACKAGE=false
``` 
and
```
module "lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "1.28.0"
  ...
 }
```

The terraform output:
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.notify_slack.module.lambda.null_resource.archive[0] must be replaced
-/+ resource "null_resource" "archive" {
      ~ id       = "498261604347341722" -> (known after apply)
      ~ triggers = { # forces replacement
            "filename"  = "builds/379c9c6df2795a46e963c1406d620f99117b2ee41f1227e974232077ecfb5357.zip"
          ~ "timestamp" = "1631072728864032000" -> "<WARNING: Missing lambda zip artifacts wouldn't be restored>"
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy. 
```

**Comment by antonbabenko** [comment]
@minokyo First of all, please try to upgrade the module to the latest (v2.16.0 as of today). There were some improvements and bug fixes implemented over time.

More specifically, you probably will have an easier pipeline if you set `recreate_missing_package = true` which was introduced in #181.

If the problem persists, please open a new issue using the latest version of this module.
