### ISSUE TITLE
Why generate a new hash/filename based on runtime?

### ISSUE THREAD

**Issue by jorwoods** [terraform-aws-modules/terraform-aws-lambda#109]
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/2f89c5d42f746abf1b9d9a1543f03354957db2f9/package.py#L1054

This line makes it so that the `content_hash` changes on every rerun, regardless of whether or not the source code has changed. This causes issues with our drift detection. Is there a reason I am not thinking of to have runtime factored into the filename, and as a result whether or not terraform tries to deploy new artifacts?

Would it not be better to leave this out and only redeploy if the underlying source or dependencies change?

**Comment by ahlinc** [comment]
@jorwoods The `package.py` script uses a same python version as specified in the runtime to install its dependencies, this is need in case of dependencies that contain binary python modules to be sure that they were compiled with correct python version. So in case of the `runtime` parameter changing such binary modules need to be recompiled to be sure that they will work correctly on the lambda environment. This peculiarity relevant for Python runtimes and I'm not completely sure about all other runtimes supported by AWS Lambda.
