### ISSUE TITLE
Lambda deploy script failure

### ISSUE THREAD

**Issue by alexedwardjones** [terraform-aws-modules/terraform-aws-lambda#118]
**Summary**

The [deployment script](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/modules/deploy/main.tf#L34) for the lambda deploy module is failing in my setup.

![image](https://user-images.githubusercontent.com/5364820/109435457-783a0380-7a12-11eb-8d08-45b2ab50daf2.png)

I believe this is because the script gets run in the `/bin/sh` shell which doesn't support the double square brackets. 

**Potential Fix**

Could the fix be as simple as setting the interpreter to `/bin/bash`?

https://www.terraform.io/docs/language/resources/provisioners/local-exec.html#interpreter

**Comment by antonbabenko** [comment]
Thanks for the report and `interpreter` is now supported as a module argument (and it uses `/bin/bash -c`, by default). Ref: https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/92/files#diff-bc2f2fc8cab216f176d3974258485159272113b47e5e19ab9fb23021d608dd1cR43-R47

[v1.41.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.41.0) has been just released.

**Comment by alexedwardjones** [comment]
Thank you!
