### ISSUE TITLE
Lack of s3_bucket option.

### ISSUE THREAD

**Issue by tcharewicz** [terraform-aws-modules/terraform-aws-lambda#119]
Hello,

I would like to set options:
- server_side_encryption to AES256
- ACL to bucket-owner-full-control

when the object is uploaded to s3_bucket. 

--
Regards 
TomekC.

**Comment by antonbabenko** [comment]
You are right, this is not supported at the moment, pull-request is welcome.

**Comment by tcharewicz** [comment]
PR is waiting for a review, could you check it?

**Comment by antonbabenko** [comment]
Fixed in #120 

[v1.42.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.42.0) has been just released.
