### ISSUE TITLE
Lambda function is not ready for use right away?

### ISSUE THREAD

**Issue by richardgavel** [terraform-aws-modules/terraform-aws-lambda#122]
If I use this module, isn't there a chance the lambda doesn't have the right permissions to invoke right away, since the lambda function only depends upon the role and not any of the attached policies? I get the following issue when using a null_resource with an "aws lambda invoke" call an exploring using public modules to reduce repeated mistakes.

"The role defined for the function cannot be assumed by Lambda"

**Comment by antonbabenko** [comment]
Please [choose and follow the template](https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/new/choose) when you open issue in this repository (or ask on discuss.hashicorp.com or [StackOverflow where more Terraform users are](https://stackoverflow.com/questions/36419442/the-role-defined-for-the-function-cannot-be-assumed-by-lambda)).
