### ISSUE TITLE
Python - pip install --no-deps

### ISSUE THREAD

**Issue by andormarkus** [terraform-aws-modules/terraform-aws-lambda#123]
Hi All,

In the current implementation when we want to create a lambda python package there is no option to use '--no-deps' flag.
If you want to run 'pip install --no-deps' than you have to go through the 'commands' option.

It would be great if the following TF variable could be added to the code
'pip_requirements_no-deps' defaults to 'false'.

Thanks,
Andor

**Comment by antonbabenko** [comment]
Hi @andormarkus !

This addition would make sense if python would be the only supported language and if there would be no other flags individual users may want to provide to `pip`. Also, there can be multiple sources provided.

It is much better for us (maintainers) to allow any customization using `commands`.

Closing this issue.

**Comment by pdecat** [comment]
I too would like to pass `--no-deps` to pip as we are using poetry to manage project dependencies and fully generate the `requirements.txt` file so [pip's dependency resolver is not needed](https://github.com/python-poetry/poetry/issues/3472#issuecomment-973170415).

How about adding a `pip_args` variable to allow passing arbitrary arguments to pip? Would a PR providing this be accepted?

Using `commands` prevents usage of the `build_in_docker` feature which is kind of a blocker for us.
