### ISSUE TITLE
Database Proxies

### ISSUE THREAD

**Issue by tnesztler** [terraform-aws-modules/terraform-aws-lambda#128]
## Is your request related to a new offering from AWS?
This feature has been available for at least 6 months.
See AWS Blog post https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/

## Is your request related to a problem? Please describe.
We cannot add a database proxy to a Lambda function using Terraform (or couldn't find how to do it using the docs)

## Describe the solution you'd like.
Ability to add an RDS database proxy using Terraform.

## Describe alternatives you've considered.
Doing it manually after deployment of the Lambda functions.

**Comment by svenlito** [comment]
@tnesztler this doesn't even exist in the Terraform AWS provider yet. However, it'd be perfectly reasonable to use this lambda module together with https://github.com/clowdhaus/terraform-aws-rds-proxy

**Comment by svenlito** [comment]
Closing this for now, please reopen once this functionality is available in https://github.com/hashicorp/terraform-provider-aws

**Comment by d8aninja** [comment]
Can we reopen this and vote for its inclusion in an upcoming release?
