### ISSUE TITLE
An argument named "lambda_role_arn" is not expected here

### ISSUE THREAD

**Issue by debu99** [terraform-aws-modules/terraform-aws-lambda#132]
Error: Unsupported argument

  on main.tf line 169, in module "lambda":
 169:   lambda_role_arn                   = aws_iam_role.lambda_role.arn

An argument named "lambda_role_arn" is not expected here.

$ terraform version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/archive v2.1.0
+ provider registry.terraform.io/hashicorp/aws v3.32.0

**Comment by antonbabenko** [comment]
Please fill in the [issue template](https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/new?assignees=&labels=&template=bug_report.md) when opening an issue, and see code in the examples folder to see it all in action.
