### ISSUE TITLE
No such file or directory "package.py" with -chdir option

### ISSUE THREAD

**Issue by alexedwardjones** [terraform-aws-modules/terraform-aws-lambda#135]
### Summary
I'm using terraform with the [chdir](https://www.terraform.io/docs/cli/commands/#switching-working-directory-with-chdir) option to change the working directory to a subdirectory called `tf`.

```
package.json
src/
tf/
   .terraform
   main.tf
   lambda.tf
```
So all of my commands look like this:
- `terraform -chdir=tf init`
- `terraform -chdir=tf apply`

I'm getting an error that looks like the following...

`3.9.1/bin/python3: can't open file ... /.terraform/modules/lambda_function/package.py': [Errno 2] No such file or directory`

I believe that this might be caused by this line and the `"${path.module}/package.py"` no longer referencing the correct path.

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/bd13b8897ed219e235f92429badfe26aa51730d8/package.tf#L10

I tried removing the line below and then it seems to work with and without the `chdir` option.

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/bd13b8897ed219e235f92429badfe26aa51730d8/package.tf#L11

**Comment by antonbabenko** [comment]
Fixed in #136

[v1.46.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.46.0) has been just released.
