### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by JimBeam2019** [terraform-aws-modules/terraform-aws-lambda#144]
## Description

While implementing terraform aws modules, I encountered the error below at the end of the process after `terraform apply`.

> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for module.lambda_function_in_vpc.aws_lambda_function.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .source_code_hash: was cty.StringVal("07fnZ38puKEHcwPIuaGymBqATq152C/Z2aoxLMWPRH0="), but now cty.StringVal("QEc9FactlOpwYYSoFSypHewANDU30G0dhbNDfMmltFM=").

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: v0.14.8

 - Provider(s):
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

 - Module: **api_gateway_v2**, **aurora**, **lambda_function_in_vpc** and **vpc**

## Reproduction

1. Create all the source files and a build folder in the root directory.
2. Run `yarn install` to add all dependencies for node.js.
3. Run the cli below to build AWS infrastructure.

```
terraform fmt
terraform init
terraform plan
terraform apply
```

### Code Snippet to Reproduce

package.json
```
{
  "name": "aws-vpc",
  "version": "1.0.0",
  "description": "AWS VPC",
  "engines": {
    "node": ">=14.15.1"
  },
  "main": "index.js",
  "author": "J.B.",
  "license": "MIT",
  "private": true,
  "scripts": {
    "start": "babel-watch index.js",
    "production-install": "yarn install --modules-folder=./build/node_modules --production=true",
    "zip-handler": "yarn run production-install && cp index.js ./build/index.js && cd ./build && zip -r index.zip ."
  },
  "dependencies": {
    "dotenv": "^8.2.0"
  }
}
```
index.js
```
'use strict';

require('dotenv').config();

exports.handler = (event, context, callback) => {
    const body = {
        user: process.env.PGUSER,
        host: process.env.PGHOST,
        database: process.env.PGDB,
        password: process.env.PGPASS,
        port: process.env.PGPORT,
    };

    callback(null, body);
}
```
api_gateway_v2.tf
```
module "api_gateway_v2" {
  source = "terraform-aws-modules/apigateway-v2/aws"

  name          = "Lambda Aurora"
  protocol_type = "HTTP"

  cors_configuration = {
    allow_headers = ["content-type", "x-amz-date", "authorization", "x-api-key", "x-amz-security-token", "x-amz-user-agent"]
    allow_methods = ["*"]
    allow_origins = ["*"]
  }

  create_api_domain_name = false

  integrations = {
    "ANY /" = {
      lambda_arn             = module.lambda_function_in_vpc.this_lambda_function_arn
      payload_format_version = "2.0"
      timeout_milliseconds   = 12000
    }

    "$default" = {
      lambda_arn = module.lambda_function_in_vpc.this_lambda_function_arn
    }
  }

  vpc_links = {
    my-vpc = {
      name               = "my-vpc"
      security_group_ids = [module.vpc.default_security_group_id]
      subnet_ids         = module.vpc.public_subnets
    }
  }

  tags = {
    Name = "private-api"
  }
}
```
aurora.tf
```
module "aurora" {
  source = "terraform-aws-modules/rds-aurora/aws"

  name                  = local.name
  engine                = "aurora-postgresql"
  engine_version        = "11.9"
  instance_type         = "db.r5.large"
  instance_type_replica = "db.t3.medium"

  vpc_id                = module.vpc.vpc_id
  db_subnet_group_name  = module.vpc.database_subnet_group_name
  create_security_group = true
  allowed_cidr_blocks   = module.vpc.private_subnets_cidr_blocks

  replica_count                       = 2
  iam_database_authentication_enabled = true
  create_random_password              = false

  username = var.db_username
  password = var.db_password

  apply_immediately   = true
  skip_final_snapshot = true

  db_parameter_group_name         = aws_db_parameter_group.example.id
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.example.id
  enabled_cloudwatch_logs_exports = ["postgresql"]

  tags = local.tags
}

resource "aws_db_parameter_group" "example" {
  name        = "${local.name}-aurora-db-postgres11-parameter-group"
  family      = "aurora-postgresql11"
  description = "${local.name}-aurora-db-postgres11-parameter-group"
  tags        = local.tags
}

resource "aws_rds_cluster_parameter_group" "example" {
  name        = "${local.name}-aurora-postgres11-cluster-parameter-group"
  family      = "aurora-postgresql11"
  description = "${local.name}-aurora-postgres11-cluster-parameter-group"
  tags        = local.tags
}
```
deploy.tf
```
resource "null_resource" "lambda_deploy" {

  provisioner "local-exec" {
    command     = "yarn run zip-handler"
  }
}
```
lambda.tf
```
module "lambda_function_in_vpc" {
  source = "terraform-aws-modules/lambda/aws"

  depends_on = [
    null_resource.lambda_deploy,
    module.aurora
  ]

  function_name = "postgras-lambda"
  description   = "Lambda function"

  handler = "index.handler"
  runtime = "nodejs12.x"

  publish = true

  create_package         = false
  local_existing_package = "${local.codebase_path}/build/index.zip"

  environment_variables = {
    PGHOST = module.aurora.this_rds_cluster_endpoint,
    PGPORT = module.aurora.this_rds_cluster_port,
    PGDB   = module.aurora.this_rds_cluster_database_name,
    PGUSER = module.aurora.this_rds_cluster_master_username,
    PGPASS = module.aurora.this_rds_cluster_master_password,
  }

  attach_network_policy  = true
  vpc_subnet_ids         = module.vpc.private_subnets
  vpc_security_group_ids = [module.vpc.default_security_group_id]

  allowed_triggers = {
    AllowExecutionFromAPIGateway = {
      service    = "apigateway"
      source_arn = "arn:aws:execute-api:${var.region}:${var.account_id}:${module.api_gateway_v2.this_apigatewayv2_api_id}/*/*/"
    }
  }
}
```
locals.tf
```
locals {
  name          = "postgresql"
  region        = var.region
  codebase_path = abspath("${path.module}/..")
  tags = {
    Owner       = "user"
    Environment = "dev"
  }
}
```
main.tf
```
provider "aws" {
  profile = "default"
  region  = var.region

  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = true
  skip_region_validation      = true
  skip_credentials_validation = true
  skip_requesting_account_id  = true
}
```
terraform.tfvars
```
region     = "us-east-1"
account_id = "1234567890"
cidr       = "10.99.0.0/18"
public_subnets = [
  "10.99.0.0/24",
  "10.99.1.0/24",
  "10.99.2.0/24"
]
private_subnets = [
  "10.99.3.0/24",
  "10.99.4.0/24",
  "10.99.5.0/24"
]
database_subnets = [
  "10.99.7.0/24",
  "10.99.8.0/24",
  "10.99.9.0/24"
]
db_username = "dbmaster"
db_password = "Password456"
```
variables.tf
```
variable "region" {
  description = "AWS Region"
  type        = string
}

variable "account_id" {
  description = "AWS Account ID"
}

variable "cidr" {
  description = "CIDR"
  type        = string
}

variable "public_subnets" {
  description = "Public subnets"
  type        = list(string)
}

variable "private_subnets" {
  description = "Private subnets"
  type        = list(string)
}

variable "database_subnets" {
  description = "Database subnets"
  type        = list(string)
}

variable "db_username" {
  description = "The username for the DB master user"
  type        = string
  sensitive   = true
}

variable "db_password" {
  description = "Database Password"
  type        = string
}
```
versions.tf
```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}
```
vpc.tf
```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = local.name
  cidr = var.cidr

  azs              = ["${local.region}a", "${local.region}b", "${local.region}c"]
  public_subnets   = var.public_subnets
  private_subnets  = var.private_subnets
  database_subnets = var.database_subnets

  enable_nat_gateway = false
  single_nat_gateway = true

  tags = local.tags
}
```

## Expected behavior

A lambda function and postgresql aurora in a VPC are built.

## Actual behavior

It returns error.

### Terminal Output Screenshot(s)

> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for module.lambda_function_in_vpc.aws_lambda_function.this[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .source_code_hash: was cty.StringVal("07fnZ38puKEHcwPIuaGymBqATq152C/Z2aoxLMWPRH0="), but now cty.StringVal("QEc9FactlOpwYYSoFSypHewANDU30G0dhbNDfMmltFM=").

**Comment by antonbabenko** [comment]
Thanks a lot for the detailed issue report!

I read this code and I think the problem is related to the fact that zip-archive is not yet created before Lambda function is using it `terraform plan`.

You have two options:
1. Run `yarn run zip-handler` before running `terraform plan` and reference the archive:

```
$ terraform apply -target=null_resource.lambda_deploy  # <- build zip-archive
$ terraform apply   # <- deploy it all
```

2. Let this module handle the creation of the package itself (create_package = true). See examples in the repo.

**Comment by JimBeam2019** [comment]
> Thanks a lot for the detailed issue report!
> 
> I read this code and I think the problem is related to the fact that zip-archive is not yet created before Lambda function is using it `terraform plan`.
> 
> You have two options:
> 
>     1. Run `yarn run zip-handler` before running `terraform plan` and reference the archive:
> 
> 
> ```
> $ terraform apply -target=null_resource.lambda_deploy  # <- build zip-archive
> $ terraform apply   # <- deploy it all
> ```
> 
>     1. Let this module handle the creation of the package itself (create_package = true). See examples in the repo.

Thank you very much for your quick reply, @antonbabenko 

I've tried both options. For the 1st one, it was stuck at creating `module.lambda_function_in_vpc.aws_lambda_function.this[0]` for over 30 minutes with no stopping after the second `terraform apply`. About the 2nd one, it returned a new error below after `terraform plan`. So far, neither option is working.

> Error: command "python3" failed with no error message
>  
>    on .terraform/modules/lambda_function_in_vpc/package.tf line 7, in data "external" "archive_prepare":
>     7: data "external" "archive_prepare" {

**Comment by antonbabenko** [comment]
Let's look at both of these options deeper:
1. `terraform apply -target=null_resource.lambda_deploy` or run `yarn run zip-handler` manually should produce just zip-archive which should be passed in the lambda module as a string argument ([sample](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/build-package/main.tf#L239-L240)).

Try to see what is wrong with the VPC creation since it is not related to the packaging issue. You can try to run the [with-vpc example](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/examples/with-vpc).

2. `python3` binary is required in the `PATH`. Python3.6 or newer.

**Comment by JimBeam2019** [comment]
Hi @antonbabenko, sorry for the late reply. Actually, what I got wrong was using packaging when I didn't mean to. The issue solved after changing the **local_existing_package** to **source_path** at the module _lambda_function_. Many thanks.
