### ISSUE TITLE
lambda_at_edge = true does not deploy into us-east-1

### ISSUE THREAD

**Issue by hemzet** [terraform-aws-modules/terraform-aws-lambda#150]
Deploying infrastructure in a single region including a Lambda function. 
However, setting lambda_at_edge = true does not change the region the Lambda function is deployed into but deploys it into the default region of the infrastructure script. Providing another region via provider=aws.edge is not suppported.

## Versions
 - Terraform: 14.5
 - Provider(s): AWS 3.37.0 - 3.40.0
 - Module: 2.0.0

## Reproduction
1. Create folder for infrastructure and add some recources (S3, Lambda@Edge, etc.)
2. Set provider region to eu-west-1
3. Run terraform init
4. Run terraform apply

### Code Snippet to Reproduce
module "lambda_edge" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 2.0"
  function_name = "cloudfront-edge-function"
  description   = ""
  handler       = "index.lambda_handler"
  runtime       = "nodejs12.x"
  publish = true
  lambda_at_edge = true
  source_path = "path to folder with js file"
  environment_variables = {
    s3_bucket_domain = aws_s3_bucket.my-bucket.bucket_regional_domain_name
  }
}

## Expected behavior
If parameter lambda_at_edge is set to true, the region for deploying the Lambda function into is set to us-east-1, independently from the region used for other resources.

## Actual behavior
Lambda function is deployed into region set for all resources.

**Comment by antonbabenko** [comment]
Hi,

`provider` block should always be outside of the module. This is a golden rule in Terraform.

It is up to a user to define how to configure the provider (credentials and region).

**Comment by hemzet** [comment]
Well, I agree, the provider block is set outside of a module. Nevertheless, for deploying Lambda to an Edge location as part of many other resources we must set us-east-1 specifically for this module. How else can I use the module as part of other resources to be deployed not in us-east-1 then?

**Comment by antonbabenko** [comment]
You can pass provider explicitly, as described here - https://www.terraform.io/docs/language/modules/develop/providers.html#passing-providers-explicitly

```
# The default "aws" configuration is used for AWS resources in the root
# module where no explicit provider instance is selected.
provider "aws" {
  region = "us-west-1"
}

# An alternate configuration is also defined for a different
# region, using the alias "us-east-1".
provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"
}

# An example child module is instantiated with the alternate configuration,
# so any AWS resources it defines will use the us-east-1 region.
module "example" {
  source    = "terraform-aws-modules/lambda/aws"

  lambda_at_edge = true

  providers = {
    aws = aws.us-east-1
  }
}
```

**Comment by hemzet** [comment]
Thanks, missed the {}
