### ISSUE TITLE
destination_config for event_source_mapping not working

### ISSUE THREAD

**Issue by byrneo** [terraform-aws-modules/terraform-aws-lambda#151]
## Description

Setting a `destination_config` block within `event_source_mapping` doesn't appear to have any effect. 

```
dynamodb_items_history = {
            event_source_arn  = xxxxx
            starting_position = "LATEST"
            destination_config = {
                on_failure = {
                    destination_arn = xxxxx
                }
            }
        }
```
Looking at the source in `main.tf` it appears to be commented out. Will this be enabled in an upcoming release?

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by antonbabenko** [comment]
Good catch. Please open a PR if you can, and update `examples/event-source-mapping`.

@svenlito do you remember if there were any issues with this in provider or any other reasons back in February?

**Comment by svenlito** [comment]
> @svenlito do you remember if there were any issues with this in provider or any other reasons back in February?

I remember you've had issues with it not being updated/delete when the plan changed. This was a few provider versions back. Might be worth reevaluating.

**Comment by antonbabenko** [comment]
@byrneo Please raise a PR if you can.

**Comment by byrneo** [comment]
@antonbabenko @svenlito  I created https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/152

The pre-commit hook re-formatted some unrelated code but i added those to the PR

**Comment by antonbabenko** [comment]
Thanks, @byrneo !

[v2.1.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.1.0) has been just released.
