### ISSUE TITLE
[support] How to create inline policy for lambda iam role?

### ISSUE THREAD

**Issue by mythily90** [terraform-aws-modules/terraform-aws-lambda#154]
## Description
Hi Team,

How to create inline policy for lambda role? I dont want managed policy to be created since it will be used only by this lambda, so no need to share for other roles.
I tried  "policy_statements", "attach_policy_jsons", "policy_json", all are creating managed policy only. With policy_statements, the name of the policy is appended with _inline_ but still the policy created is managed one. Am I missing something?

Terraform Version being used - 

$terraform -version
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.41.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

snippet used:

`attach_policy_statements = true
 policy_statements = {
   iam = {
      effect    = "Allow",
      actions   = ["iam:AddUserToGroup"],
      resources = ["arn:aws:iam::${local.account_id}:group/abc"]
    }
  }`

**Comment by antonbabenko** [comment]
Hi,

You need to use `policy_json`, like this:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/05817a29370b410d79fcc55122fa6062848be91a/examples/complete/main.tf#L63-L77

In any case, the policy will have to be created and then attached to a role.
