### ISSUE TITLE
 Autogenerated module documentation can't deal with check boxes

### ISSUE THREAD

**Issue by FRosner** [terraform-aws-modules/terraform-aws-lambda#155]
## Description

Autogenerated module documentation can't deal with check boxes: https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest

## Expected behavior

It's probably simplest to remove the check boxes since they are all checked anyway.

## Actual behavior

![image](https://user-images.githubusercontent.com/3427394/119455155-9d9c8c00-bd39-11eb-9695-0141a2f97ea4.png)

**Comment by antonbabenko** [comment]
Yes, the registry website does not know GitHub flavored markdown. Thank you for updating this one!

I just looked into other modules where the same issue may exist:
- https://github.com/terraform-aws-modules/terraform-aws-step-functions
- https://github.com/terraform-aws-modules/terraform-aws-eventbridge
- https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2
- https://github.com/terraform-aws-modules/terraform-aws-notify-slack
- https://github.com/terraform-aws-modules/terraform-aws-pricing

If you can, please fix the same in those modules also. No push. :)

**Comment by FRosner** [comment]
Made a bunch of PRs in the repos. Let me know if this is enough / feel free to modify it to your liking :)

**Comment by antonbabenko** [comment]
Thank you, all merged!
