### ISSUE TITLE
add support for event_source_mapping on alias submodule

### ISSUE THREAD

**Issue by gibzon** [terraform-aws-modules/terraform-aws-lambda#159]
it would be good to have support for adding event_source_mapping on the alias submodule just like it is present on the main module.

it would reach more use cases that way :)

thanks for the great work!

**Comment by antonbabenko** [comment]
Good point! Pull request is welcome if anyone has time.

**Comment by assinnata** [comment]
Any news on this enhancement? I am stuck on a use case where I need to deploy multiple aliases with mq triggers listening on the same queue

**Comment by assinnata** [comment]
I'll try to take a look into it
