### ISSUE TITLE
Use local_existing_package with store_on_s3

### ISSUE THREAD

**Issue by ofhouse** [terraform-aws-modules/terraform-aws-lambda#16]
Hello,

I want to use a prebuilt local zip-package together with the `store_on_s3` option but unfortunately it results in an error:

```sh
Error: "s3_bucket": conflicts with filename

  on .terraform/modules/image_resize/terraform-aws-lambda-1.3.0/main.tf line 14, in resource "aws_lambda_function" "this":
  14: resource "aws_lambda_function" "this" {

Error: "filename": conflicts with s3_bucket

  on .terraform/modules/image_resize/terraform-aws-lambda-1.3.0/main.tf line 14, in resource "aws_lambda_function" "this":
  14: resource "aws_lambda_function" "this" {
```
 
My configuration is as follows:
```tf
module "image_resize" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = "my-function"
  description   = "Managed by Terraform"
  handler       = "handler.handler"
  runtime       = "nodejs12.x"

  create_package         = false
  local_existing_package = "../path/to/package.zip"

  store_on_s3 = true
  s3_bucket   = "some-aws-bucket"
}
```

It seems like the configuration sets both the `filename` and the `s3_bucket` key on the `aws_lambda_function` resource which results in this error.

**Comment by ofhouse** [comment]
Looked at the code and hoped to find a quick fix, but it seems that this would require a little more effort to implement.
btw Huge props for writing and maintaining all the logic in this module! 💯

In the meantime for everyone facing the same issue here is a simple workaround to archive the desired behaviour:

```tf
locals {
  my_function_source = "../path/to/package.zip"
}

resource "aws_s3_bucket_object" "my_function" {
  bucket = "some-aws-bucket"
  key    = "${filemd5(local.my_function_source)}.zip"
  source = local.my_function_source
}

module "my_function" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = "my-function"
  description   = "Managed by Terraform"
  handler       = "handler.handler"
  runtime       = "nodejs12.x"

  create_package      = false
  store_on_s3         = true
  s3_existing_package = {
    bucket = "some-aws-bucket"
    key    = aws_s3_bucket_object.my_function.id
  }
}
```

**Comment by antonbabenko** [comment]
Hi!

Thanks for opening issue.

This is the right workaround for your case because storing files on S3 is the responsibility of `aws_s3_bucket_object` resource (you can build a package (`create_package = true`) and `store_on_s3 = true` to store it on S3 using this module, but you can't store prebuilt artifacts).

I will make an update to README soon.
