### ISSUE TITLE
Add support for Docker Image creation and upload as a part of Lambda/Layer creation.

### ISSUE THREAD

**Issue by Barteus** [terraform-aws-modules/terraform-aws-lambda#160]
## Problem
There is a deployment to the S3 bucket, but there is no easy way to create Docker Image and deploy lambda using this Image

## Proposed solution
It would be nice to be able to name an ECR (own or created in this module), create an Image and create lambda using this Image. There is a nice docker plugin we can leverage to do so - https://registry.terraform.io/providers/kreuzwerker/docker/latest 

## Alternative - use now
The natural alternative is to keep the artefact creation out of infrastructure creation.

**Comment by antonbabenko** [comment]
Thanks for opening this issue.

I agree that it would be helpful to know how to build Docker images and make them used by this module but I also think that it should not be a required part of the module (rather a submodule).

I have recently published a similar behavior in another module - https://github.com/cloudquery/terraform-aws-cloudquery/blob/34c04bd391c24d67c9dc3b026f6dffac96230354/main.tf#L111-L112

If you or anyone wants to implement it here and update documentation, it would be great.

**Comment by Barteus** [comment]
Please assign this task to me. I will add ECR as a part of optional variable - similar way like in cloudquery repo.

**Comment by rogermyung** [comment]
I've started work on adding support for container images

**Comment by antonbabenko** [comment]
@Barteus Good, the main difference between this Lambda module and Cloudquery repo is that the Cloudquery repo is using this module. Let's make all docker building resources for Lambda in a submodule.

**Comment by Barteus** [comment]
@antonbabenko I have created a draft for the implementation (https://github.com/Barteus/terraform-aws-lambda/tree/160-docker-image-support).
I have a problem with dependencies for examples - complete and with-etf.
The error messages on terraform init it:
`
Error: Module does not support for_each

on main.tf line 268, in module "lambda_function_for_each":
 268:   for_each = toset(["dev", "staging", "prod"])

Module "lambda_function_for_each" cannot be used with for_each because it
contains a nested provider configuration for "docker", at
../../modules/build/main.tf:8,10-18.

This module can be made compatible with for_each by changing it to receive all
of its provider configurations from the calling module, by using the
"providers" argument in the calling module block.
`

I have found some information here: https://www.terraform.io/docs/language/modules/develop/providers.html but I could not solve it in any way. Can you help me a bit here?

**Comment by antonbabenko** [comment]
@Barteus Which version of Terraform do you use?

I look into your branch - https://github.com/terraform-aws-modules/terraform-aws-lambda/compare/master...Barteus:160-docker-image-support?expand=1 - and not sure this is what we need.

We already have support for 99% of container images in this module. Here is an example - https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/container-image/main.tf

The only remaining part can be that we make a submodule in `modules/ecr-docker-image` with the code very similar to these lines - https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/container-image/main.tf#L31-L65

There should be no changes to the main module such as dependency on the submodules.

**Comment by Barteus** [comment]
@antonbabenko My version - `Terraform v0.14.3`

Please take a look now - I have adjusted the module and it works.
