### ISSUE TITLE
Slim python lambdas

### ISSUE THREAD

**Issue by rdkls** [terraform-aws-modules/terraform-aws-lambda#161]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
No. 
Well yes, if you hit the 250mb uncompressed lambda limit

## Describe the solution you'd like.
This is just a suggestion which I found helpful in my own module, akin to the serverless framework "slim" feature https://www.serverless.com/plugins/serverless-python-requirements

In my own incarnation of this module, I do the following
- Strips shared object files ca. 20% saving
- Remove .py, use .pyc's = faster lambda and ca. 20% saving
- Remove tests, info (minor savings, but why not)
- Remove packages that will be available in AWS lambda environment (boto3 et al) ca. 50mb (uncompressed)

If you're interested, the commands I used to do so were:
```
find . -name *\\.pyc -exec mv '{}' . ; 
find . -name *\\.so -exec strip '{}' ; 
find . -type d -name *-info -prune -exec rm -rdf '{}' ; 
find . -type d -name tests -prune -exec rm -rdf '{}' ; 
find . -type d -name boto3 -prune -exec rm -rdf '{}' ; 
find . -type d -name botocore -prune -exec rm -rdf '{}' ; 
find . -type d -name docutils -prune -exec rm -rdf '{}' ; 
find . -type d -name dateutil -prune -exec rm -rdf '{}' ; 
find . -type d -name jmespath -prune -exec rm -rdf '{}' ; 
find . -type d -name s3transfer -prune -exec rm -rdf '{}' ; 
find . -type d -name doc -prune -exec rm -rdf '{}' ; 
```

## Describe alternatives you've considered.
The new support for docker in lambdas

**Comment by antonbabenko** [comment]
It is completely up to developers to specify what they want to install and keep in the produced artifacts. We also support Container Images and Zip archive formats in this module.

Please see the examples code in this module for more.
