### ISSUE TITLE
Lambda not update when s3_existing_package is used

### ISSUE THREAD

**Issue by atrinchillo-mwb** [terraform-aws-modules/terraform-aws-lambda#163]
## Description

Consider this scenario.
We build package and put the lambda_functions.zip on an S3 with a pipeline.
We after deploy lambda with this terraform module

The problem is that the lambda zip file is not updated after a terraform apply.
This use case seems covered by

create_package      = false
  s3_existing_package = {
    bucket = "my-bucket-with-lambda-builds"
    key    = "existing_package.zip"
  }

It is necessary to do something else? Could you please clarify?

**Comment by antonbabenko** [comment]
Hi! You should specify version_id also to trigger update. See code in examples. 

Best regards,
Anton.

**Comment by atrinchillo-mwb** [comment]
Please let me check if I understood correctly
After the pipeline pushed the zip file in terraform we need before to retrieve version_id of the file and insert as version_id in the block that I just posted?

**Comment by atrinchillo-mwb** [comment]
Ok I think I found it
It is necessary to create the object in S3
with the object we can take every time the version_id from it and this redeploy, so the previous code part will be like:

`create_package = false
s3_existing_package = {
bucket = "my-bucket-with-lambda-builds"
key = "existing_package.zip"
version_id = "module.object.s3_version_id    # based on the module used for object creation
}`

**Comment by antonbabenko** [comment]
There is more than one way to achieve what you want. If you use Terraform to create an object on S3 then you can write something like this to update `version_id` automatically:
```
create_package = false
s3_existing_package = {
  bucket = "my-bucket-with-lambda-builds"
  key = "existing_package.zip"
  version_id = module.object.s3_version_id   # <- based on the module used for object creation
}
```

If your pipeline does it differently, you will have to run [`terraform taint`](https://www.terraform.io/docs/cli/commands/taint.html) which will force terraform to re-create the resource.

**Comment by atrinchillo-mwb** [comment]
Thank you for clarifications, it is exactly what I did :)

**Comment by kenanbiel** [comment]
Just to double clarify, if the object is created not by terraform, the only way to update the lambda function is to re-create it. Right?

**Comment by antonbabenko** [comment]
There is also a way to run “terraform import” with correct arguments but it can be a bit tricky. I would use this module to make a new function as code, verify and update references in everything like IAM, API Gateways, etc. And then just delete the old one.

Best regards,
Anton.

**Comment by kenanbiel** [comment]
Yep yep, just wondering where to draw the line regarding lambda since it's an application code. The only option for us is from the application repo, build then upload to S3. Terraform would just simply pull then deploy to Lamda which i'm now following from https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#lambda-function-with-existing-package-prebuilt-stored-in-s3-bucket.
