### ISSUE TITLE
random provider listed in versions.tf, but unused

### ISSUE THREAD

**Issue by llamahunter** [terraform-aws-modules/terraform-aws-lambda#167]
## Description

There appears to be an unnecessary requirement on the random provider in the core module

## Versions
 - Terraform:
1.0.1
 - Provider(s):
N/A
 - Module:
lambda

## Reproduction

1. Inspect versions.tf file in module.
2. Note that nothing in the module (other than examples) uses random

## Expected behavior
Only list required providers that are actually necessary for functioning of module

## Actual behavior
The random provider is listed, but unused.

**Comment by antonbabenko** [comment]
That sounds about right, please make a PR if you can.
