### ISSUE TITLE
`map` is no longer available in Terraform 1.x

### ISSUE THREAD

**Issue by dominics** [terraform-aws-modules/terraform-aws-lambda#170]
After being deprecated, the `map()` function is no longer available in the newest versions of Terraform, so this will fail under Terraform 1.0.1, for example:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/62ebcd4c239b79853ce928bcfead1bc3b0b533c7/modules/deploy/main.tf#L28

On my Terraform 1.0.1 environment, I tried replacing this `map(k, v)` call with either `tomap({ k = v })` or `tomap({ k: v })` - but neither of them works (even though they are recommended in docs, both are broken because the `k` bound variable from the for expression _becomes the literal string `"k"` rather than e.g. 'BeforeAllowTraffic'_ - it seems the bound variable is missed and treated as a bare string).

I found `zipmap([k], [v])` does work.

**Comment by antonbabenko** [comment]
Thanks a lot for opening this issue! The trick is to wrap `k` in brackets to tell Terraform that the value should be evaluated.

Fixed in #171

**Comment by antonbabenko** [comment]
[v2.6.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.6.0) has been just released.
