### ISSUE TITLE
python3 failed with no error message , Invalid value for name.

### ISSUE THREAD

**Issue by NigelDaniels-EL** [terraform-aws-modules/terraform-aws-lambda#174]
## Description
when running terraform plan I receive the  fallowing errors: 
```
Error: command "python3" failed with no error message

Error: invalid value for name (must match [\w+=,.@-])

  on .terraform/modules/lambda/iam.tf line 60, in resource "aws_iam_role" "lambda":
  60:   name                  = local.role_name

Error: invalid value for name (must match [\w+=,.@-])

  on .terraform/modules/lambda/iam.tf line 99, in resource "aws_iam_policy" "logs":
  99:   name   = "${local.role_name}-logs"

```
## Versions

 - Terraform: 0.13.6

 - Provider(s):Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/aws v3.49.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

 - Module:

## Reproduction

NO

YES 

1. terraform init 
2. terraform plan

## Expected behavior
Terraform plan to complete

## Actual behavior
error listed above

### Terminal Output Screenshot(s)
listed above

**Comment by pauljamesrussell** [comment]
@NigelDaniels-EL I had a very similar issue, and realised ultimately that my source_path wasn't resolving correctly. in my case, setting it to "${path.module}/<module-local-path>" did the trick. Hope that helps!

**Comment by antonbabenko** [comment]
+1 to what @pauljamesrussell said, also the error is - `Error: invalid value for name (must match [\w+=,.@-])`.

Make sure that `name` matches regex.
