### ISSUE TITLE
lambda module fails with errors: This is a bug in the provider, which should be reported in the provider's own issue tracker

### ISSUE THREAD

**Issue by sambonator1** [terraform-aws-modules/terraform-aws-lambda#176]
## Description

When running terraform apply, and answering yes, errors occur on module or provider.  
So far this happens only when running terraform on linux.  Has not occurred yet on Windows, running the same terraform deployment using the same remote state file on S3, same terraform/module/provider versions. 

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

Above steps already done.

## Versions
lambda module 2.7.0
 - Terraform:
1.0.2
 - Provider(s):
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.49.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

 - Module:
lambda

## Reproduction
terraform apply -auto-approve
delete builds, .terraform, .terraform.lock.hcl
terraform init
terraform apply -auto-approve

## Expected behavior
Successful deployment

## Actual behavior
Gives error messages and deployment fails. 

### Terminal Output Screenshot(s)
...
module.ovens.module.lambda_layer_s3.null_resource.archive[0] (local-exec): Created: builds/8a7fd13c0ab812ab589223bde49b7a1668e50b64378198fc7afa4a005ea315cb.zip
module.ovens.module.lambda_layer_s3.null_resource.archive[0]: Creation complete after 14s [id=4243379649972124456]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataPackager.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataPackager.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("608607b2a80d11f0a01018fb73c26756"), but now
│ cty.StringVal("60f931f3825cc7753a4318b99980627e").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensResponseSaver.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensResponseSaver.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("fc3833ed6fc74abb6f5600b6c22bbfc4"), but now
│ cty.StringVal("8b262f793efc045ade10f20db9decea6").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDashboardDBQuery.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("94fbbda178df0a9cedcf94b0307e6d56"), but now
│ cty.StringVal("f85ace5fa4cef7316d7ffcdb1d2953b8").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDashboardDBQuery.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataTransformer2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataTransformer2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("1e2a5aceb35e59a5dacc6c8413c8f73b"), but now
│ cty.StringVal("8acb07cc8272117245c69bd824e766e1").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataEncoder2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataEncoder2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("e8c7326c98aaad59feb8341cad328a00"), but now
│ cty.StringVal("81b1ff5e0f383caa02590e6791770e03").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensCheckOvens.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("bb990aaebac430c9c4cdfef1539ca595"), but now
│ cty.StringVal("259b92882d331b340be434618a2c0b4f").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensCheckOvens.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDashboardDBInsert.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("d53f877d1ba135c53afcefc60b2d71f5"), but now
│ cty.StringVal("cdb91e4e6a2e22faa94e4effc9e957f6").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDashboardDBInsert.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_InsertOvensMap.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_InsertOvensMap.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("5cfe3398dd4fd739fee3ad5888c8c197"), but now
│ cty.StringVal("f8e0aa7e1de11ac8cec91b2892a004b5").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensTimestreamInsert2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensTimestreamInsert2.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("4fd89907f2d4335845af77a7d966d249"), but now
│ cty.StringVal("9401d14d4390b9fe2bbaa21dd7a7133c").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_UpdateOvensGLTagInMem.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_UpdateOvensGLTagInMem.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("47ee6e0a4ac370882827fb1c750c8ea1"), but now
│ cty.StringVal("ad6ac18c7a94872dc78ff2815dc89ac5").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensMapUpdate.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("d90147f350767902125214c0ad4c2c63"), but now
│ cty.StringVal("dbf19cf7f790519b9c5853e19c09005e").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensMapUpdate.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataHandler.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensDataHandler.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("29dc71cbbaea7ab5e1d68e2d8f396ecd"), but now
│ cty.StringVal("0360947f68630b246409799e234bd1af").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensResponseTransformer.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("72705230a93fa626fdd5744891e5b322"), but now
│ cty.StringVal("c3754267ec941c92674dac19b8cd238a").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensResponseTransformer.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensIoTRuleDelayCapture.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensIoTRuleDelayCapture.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("a8f7feaadbd817a738289b19a684f915"), but now
│ cty.StringVal("0070dacb08c3c1118b79465c7c506629").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensTimestreamInsert3.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("d07d8935e5b8e8be73ef1cd330144066"), but now
│ cty.StringVal("3242204a89cc2af8b8479d41a4e65543").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensTimestreamInsert3.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensIoTRuleErrorCapture.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .version_id: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.ovens.module.lambda_OvensIoTRuleErrorCapture.aws_s3_bucket_object.lambda_package[0] to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .etag: was cty.StringVal("d3b2dae173aae69418ba55d786ad457b"), but now
│ cty.StringVal("4ffc7c38f57f7fdfe973938e9774afc8").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...

## Additional context
Changed to version="2.6.0" in my module seemed to fix the above issues on trial run.  Yet further testing led to the same deployment failure later.  Also tried changing provider version to 3.48.0.  On one run the deployment succeeded.  Later trials led to the same failures.

**Comment by sambonator** [comment]
I'm going to close this issue.  This appeared to be a problem with the terraform provider, and it now appears to be resolved... cannot recreate issue anymore.

**Comment by sambonator** [comment]
I guess I can't close it.  Please close this issue.
