### ISSUE TITLE
0   I am trying to deploy nodejs lambda zip file into a private subnet custom vpc using terraform. The terraform plan works fine. But throws errors while applying the changes. The roles get created but terraform lambda doesn't deploy and errors out in a minute. Error is: "error creating Lambda Function (1): ValidationException: status code: 400, request id..."  

### ISSUE THREAD

**Issue by charlesanil** [terraform-aws-modules/terraform-aws-lambda#182]
0

I am trying to deploy nodejs lambda zip file into a private subnet custom vpc using terraform. The terraform plan works fine. But throws errors while applying the changes. The roles get created but terraform lambda doesn't deploy and errors out in a minute. Error is: "error creating Lambda Function (1): ValidationException: status code: 400, request-id..."
This lambda will be invoked by cloud watch-event.

Anything to do with VPC roles?

module "lambda" {
  providers = {
    aws.programmatic = aws.programmatic
  }
  
  source                         = "../modules/lambda"
  description                    = var.description
  filename                       = "${path.module}/filename.zip}"
  function_name                 = "rfcsyncfunc" 
  handler                        = "index.handler"
  memory_size                    = 512
  publish                        = false
  reserved_concurrent_executions = 20
  runtime                        = "nodejs14.x"
  source_code_hash               =  filebase64sha256(var.filename)
  timeout                        = 90
  
    vpc_config = {
    security_group_ids = ["sg-123456789"]  
    subnet_ids         = ["xx.xx.xxx.xxx/27","xx.xx.xx.xx/27"]  //["subnet-1", "subnet-2"]
  }

  environment = {
    variables = {
      TEST1API_URL  = "https://example.com/test.asmx"
      TEST2API_URL  = "https://example.com/test/staging/test2.asmx"
     
    }
  }

}
//lambda module
provider aws {
  alias = "programmatic"
}

resource "aws_lambda_function" "lambda" {
  description = var.description
  dynamic "environment" {
    for_each = length(var.environment) < 1 ? [] : [var.environment]
    content {
      variables = environment.value.variables
    }
  }
  filename                       = var.s3_bucket == "" ? var.filename : null
  function_name                  = var.function_name
  handler                        = var.handler
  memory_size                    = var.memory_size
  publish                        = var.publish
  reserved_concurrent_executions = var.reserved_concurrent_executions
  role                           = aws_iam_role.lambda.arn
  runtime                        = var.runtime
  source_code_hash               = var.source_code_hash
  tags                           = var.tags
  timeout                        = var.timeout

  dynamic "vpc_config" {
    for_each = length(var.vpc_config) < 1 ? [] : [var.vpc_config]
    content {
      security_group_ids = vpc_config.value.security_group_ids
      subnet_ids         = vpc_config.value.subnet_ids
    }
  }
}

data "aws_iam_policy_document" "assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "lambda" {
  name               = "${var.function_name}-lambdarole"
  assume_role_policy = data.aws_iam_policy_document.assume_role_policy.json
  permissions_boundary = var.permissions_boundary
}

resource "aws_iam_role_policy_attachment" "cloudwatch_logs" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy_attachment" "vpc_eniattachment" {
  count = length(var.vpc_config) < 1 ? 0 : 1
  role  = aws_iam_role.lambda.name  
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess"
}

/*
resource "aws_iam_role_policy_attachment" "vpc_attachment" {
  count = length(var.vpc_config) < 1 ? 0 : 1
  role  = aws_iam_role.lambda.name  
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}
*/

**Comment by xadamxk** [comment]
It doesn't seem this applies to your issue, but I was getting the same 400 error (roles would provision but the lambda itself would not) and removing any periods (`.`) from the function name fixed it for me. 

I didn't see any mention of this limitation in CloudFormation or Terraform's documentation for lambdas:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#function_name

**Comment by antonbabenko** [comment]
400 Error can mean several things - all unrelated to the module itself, so I am closing this issue.

You should be able to get a better answer on stackoverflow or similar forums.
