### ISSUE TITLE
Can't find external program python3

### ISSUE THREAD

**Issue by jrauen** [terraform-aws-modules/terraform-aws-lambda#184]
## Description

When running this module on an Terraform Enterprise server we receive the above error. It looks related to #130 but because Terraform Enterprise runs on its own docker image there's no way for us to make sure python is installed to it.

<img width="763" alt="Screen Shot 2021-07-21 at 9 59 45 AM" src="https://user-images.githubusercontent.com/72451987/126557642-5e52fa8f-3528-426d-8cd0-6661698674ef.png">

**Comment by antonbabenko** [comment]
Hi @jrauen !

You need to make sure that Python 3 is installed on the TFE Runner.

[Here](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/#using-with-terraform-cloud-agents) is a note from another module for Terraform Cloud. Hope it helps you.

**Comment by jrauen** [comment]
Yup! My coworker found this and I completely forgot I had this issue open. For any in the future who need it the Hashicorp documentation provides instructions on configuring a custom worker image for Terraform Enterprise.

https://www.terraform.io/docs/enterprise/install/installer.html#alternative-terraform-worker-image
