### ISSUE TITLE
lambda.null_resource.archive[0] must be replaced

### ISSUE THREAD

**Issue by kuntalkumarbasu** [terraform-aws-modules/terraform-aws-lambda#185]
## Description

Our Terraform runs on a Jenkins EKS cluster, so the volume is not persistent. Every time we run plan we have this 
`lambda.null_resource.archive[0] must be replaced` and `lambda.this[0]` will be updated in-place coming up. This is becoming a problem to identify the actual plan that is supposed to be deployed. I followed the FAQ and added 
`TF_RECREATE_MISSING_LAMBDA_PACKAGE=false` wherever possible but it still keeps on popping. 

1. Is there any way to update the packaging to check if there is any actual modification to the lambda file then only do the packaging and throw this in the plan.
2. or if the module takes a persistent location as an input probably a s3 location where it can go and check for the build archive that will do too.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:0-13-1

 - Provider(s):

 - Module:

## Expected behavior

I ran plan
if there is no change in code for the lambdas that should not be shown in plan

## Actual behavior

Every time we run plan we have this 
`lambda.null_resource.archive[0] must be replaced` and `lambda.this[0]` will be updated in-place coming up.

**Comment by stevewillard** [comment]
How did you resolve this issue? I'm seeing the same behavior.
