### ISSUE TITLE
Code being successfully deployed even when Lambda code is clearly broken and auto_rollback enabled

### ISSUE THREAD

**Issue by KrzysztofDerkaczewECS** [terraform-aws-modules/terraform-aws-lambda#187]
## Description

Code being successfully deployed even when Lambda code is clearly broken and auto_rollback enabled

Can you please advise how to configure deployment to auto_rollback  when lambda code doesn't work

**Comment by antonbabenko** [comment]
Please provide clear instructions and include the code you have, so that we can maybe help.

For now, I will just close this one.
