### ISSUE TITLE
Provide additional flexibility for assume_role_policy

### ISSUE THREAD

**Issue by pjungels-paraport** [terraform-aws-modules/terraform-aws-lambda#196]
I was frustrated to find that there's not a way to achieve this type of trust policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::ACCOUNT_NUM:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "SomeExternalId"
        }
      }
    }
  ]
}
```
We can already add additional principals as trusted entities to the assume_role policy document. It would be great if we could also add additional statement blocks to the assume_role policy doc.

**Comment by antonbabenko** [comment]
This is a good point. There are multiple ways users can build the policies (even assume_role policies), so we probably need to implement it in a way similar to this one which will be in addition to the existing `statement` block in `assume_role` policy document:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/8556dbc7ea2fd44c8f05401a2c4e71bfbe708f19/iam.tf#L302-L338

PR is welcome.
