### ISSUE TITLE
attach_network_policy = true  does not work for govcloud

### ISSUE THREAD

**Issue by kanchen** [terraform-aws-modules/terraform-aws-lambda#198]
attach_network_policy = true does not work for govcloud as policy ARN is hard coded in
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/iam.tf

**Comment by antonbabenko** [comment]
Good point! Fixed in #201.

[v2.18.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.18.0) has been just released.
