### ISSUE TITLE
Make docker_registry_image resource creation conditional respect to create_ecr_repo variable

### ISSUE THREAD

**Issue by lmolinaro** [terraform-aws-modules/terraform-aws-lambda#205]
# docker_build module
I expect that when docker_build module has _create_ecr_repo_ set to false nothing should being created.

To solve it, I think is enough to add a count conditional to the _create_ecr_repo_ as already done for _aws_ecr_repository_ resource.

Thanks

**Comment by antonbabenko** [comment]
This is the correct behavior.

There is a way to publish Docker images into an existing ECR repository (defined in `ecr_name`), so `create_ecr_repo` should be set to `false`.

**Comment by lmolinaro** [comment]
Sorry, I see now.

Anyway, generally a module should have an attribute that inhibit resources creation.
Maybe is possible to add a new variable, like `enabled`, defaulted to true to don't change current behavior.
 
Don't you agree?

**Comment by antonbabenko** [comment]
Yes, this is a good idea to add it. PR is welcome.

We normally have it in all terraform-aws-modules but here I didn't add it.

Also, we can use `count` in `module` block since Terraform 0.13 to achieve the same in Terraform.
