### ISSUE TITLE
Support selection of instruction set architecture

### ISSUE THREAD

**Issue by Temdegon** [terraform-aws-modules/terraform-aws-lambda#207]
Currently I can't find a way to provide lambda architecture, x86_64 | arm64.
See:
[https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Architectures](url)
Do you have plans to support this feature?

**Comment by antonbabenko** [comment]
#206 is about this. It will be merged soon.
