### ISSUE TITLE
Use `AWSXRayDaemonWriteAccess` instead of deprecated `AWSXrayWriteOnlyAccess`

### ISSUE THREAD

**Issue by pdecat** [terraform-aws-modules/terraform-aws-lambda#208]
## Is your request related to a new offering from AWS?

Not really.

## Is your request related to a problem? Please describe.

The `AWSXrayWriteOnlyAccess` policy is not (no longer?) documented: 
https://docs.aws.amazon.com/xray/latest/devguide/security_iam_id-based-policy-examples.html#xray-permissions-managedpolicies

It's usage is confusing: https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v2.20.0/iam.tf#L217

## Describe the solution you'd like.

Switch to the currently documented policy: `AWSXRayDaemonWriteAccess`

## Describe alternatives you've considered.

None.

## Additional context
* https://github.com/aws/serverless-application-model/issues/1401

**Comment by antonbabenko** [comment]
Strange, AWSXrayWriteOnlyAccess was present and I've used it. I can see some references when I google it but can't find anything in the official AWS docs.

Anyway, we should change it as you describe. Will you be able to make a PR?

**Comment by pdecat** [comment]
Sure, I'll submit a PR.
