### ISSUE TITLE
Could not locate source_path

### ISSUE THREAD

**Issue by emre141** [terraform-aws-modules/terraform-aws-lambda#215]
## Description
Terraform plan failed due to Could not locate source_path regarding to use  ```"${path.module}/sourcecode"```

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.62.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

 - Provider(s):
provider registry.terraform.io/hashicorp/aws v3.62.0
 - Module:
Downloading terraform-aws-modules/lambda/aws 2.20.0 for lambda_function...
- lambda_function in .terraform/modules/lambda_function
Downloading terraform-aws-modules/lambda/aws 2.20.0 for lambda_layer_local...
- lambda_layer_local in .terraform/modules/lambda_layer_local
Downloading terraform-aws-modules/cloudwatch/aws 2.1.0 for log_metric_filter...
- log_metric_filter in .terraform/modules/log_metric_filter/modules/log-metric-filter
Downloading terraform-aws-modules/lambda/aws 2.20.0 for package_dir...

## Reproduction

No

Yes

### Code Snippet to Reproduce
terragrunt plan

## Expected behavior
I expected to success plan output
## Actual behavior
[terragrunt] 2021/10/19 22:25:07 Running command: terraform plan -lock-timeout=20m -parallelism=40
Acquiring state lock. This may take a few moments...
module.package_file_with_pip_requirements.null_resource.archive[0]: Refreshing state... [id=2827457759683703423]
random_pet.this: Refreshing state... [id=able-jackal]
module.package_file_with_pip_requirements.local_file.archive_plan[0]: Refreshing state... [id=4b0210d0d55788bc1bb4bdbd3ece4947e01b3932]
module.package_dir.local_file.archive_plan[0]: Refreshing state... [id=659c26b6176a1e6731e90d5af8f76bb742e9f0ea]
module.package_dir.null_resource.archive[0]: Refreshing state... [id=3477677468785454566]
aws_cloudwatch_event_rule.trigger_lambda_function: Refreshing state... [id=funcChromeFeed-rule]
module.lambda_function.aws_cloudwatch_log_group.lambda[0]: Refreshing state... [id=/aws/lambda/funcChromeFeed-test]
module.lambda_function.aws_iam_role.lambda[0]: Refreshing state... [id=funcChromeFeed-test]
module.log_metric_filter.aws_cloudwatch_log_metric_filter.this[0]: Refreshing state... [id=error-metric-/aws/lambda/funcChromeFeed-test]
module.lambda_function.aws_iam_policy.logs[0]: Refreshing state... [id=arn:aws:iam::681105386544:policy/funcChromeFeed-test-logs]
module.lambda_function.aws_iam_role_policy_attachment.logs[0]: Refreshing state... [id=funcChromeFeed-test-20211012202019408900000001]

Error: failed to execute "python3": Could not locate source_path "/Users/emregundogdu/Desktop/onedio/scripts/reporting_scripts/code/seo_Chrome_Feed/builds/b41fcb4f1bc02b69b8acd0661bf2f4c7890d25b76a01a73ad75ee9d91fe1c372.zip".  Paths are relative to directory where `terraform plan` is being run ("/Users/emregundogdu/Desktop/onedio/scripts/reporting_scripts/code/seo_Chrome_Feed")

**Comment by emre141** [comment]
Yeah I just tried lots of different alternative that why are you see the artifact dir on there,  So you mean if have to use  `source_path`  in `jsonencode()` , I  would try to use `source_path = jsonencode("${path.module}/sourcecode")`, is it right? If it  is not right ,  could you share complete line of the  `source_path`  in `jsonencode()`

**Comment by emre141** [comment]
@antonbabenko  I have got similar error over again once I update `source_path` as following module call,

```
module "package_dir" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "2.20.0"
  create_function = false
  source_path = jsonencode("${path.module}/sourcecode")
  runtime     = "python3.8"
}
```
### terragrunt plan
```
Error: failed to execute "python3": Could not locate source_path ""./sourcecode"".  Paths are relative to directory where `terraform plan` is being run ("/Users/emregundogdu/Desktop/onedio/scripts/reporting_scripts/code/seo_Chrome_Feed")

```

### Folder tree
```
.
├── backend.tf
├── build
│   └── funcChromeFeed-dev-hello-test.zip
├── main.tf
├── output.tf
├── sourcecode
│   ├── client_secrets.p12
│   ├── constants.pickle
│   ├── ga_get_data.py
│   ├── handler.py
│   ├── requirements.txt
│   ├── seo_google_chrome_feed.py
│   └── slackbot_functions.py
├── terragrunt.hcl
├── variables.tf
└── version.tf
```

**Comment by antonbabenko** [comment]
I am a bit lost in the way you use terragrunt and terraform together. Why do you have `module` block and `terragrunt.hcl`?

Here is my complete `terragrunt.hcl` and I don't have any tf-files near it:

```hcl
terraform {
  source = "tfr:///terraform-aws-modules/lambda/aws?version=2.20.0"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  function_name = "function1"
  handler       = "webhook_handler.webhook_handler"
  runtime       = "python3.8"
  timeout       = 30
  memory_size   = 512

  publish = true

  // terragrunt bug: use jsonencode when "type = any"
  source_path = jsonencode("${abspath("${get_terragrunt_dir()}/../../backend")}/function1")

  artifacts_dir = abspath("${get_terragrunt_dir()}/../builds")
}
```

Try putting fixed string value into `source_path` into your code to avoid using variables and HCL/terragrunt functions to begin with.

**Comment by emre141** [comment]
I didn't understand enough could you refactor `source_path = jsonencode("${abspath("${get_terragrunt_dir()}/../../backend")}/function1")
` as my directory tree onces for me ?

My Directory Tree
```
.
├── backend.tf
├── build
│   └── funcChromeFeed-dev-hello-test.zip
├── main.tf
├── output.tf
├── sourcecode
│   ├── client_secrets.p12
│   ├── constants.pickle
│   ├── ga_get_data.py
│   ├── handler.py
│   ├── requirements.txt
│   ├── seo_google_chrome_feed.py
│   └── slackbot_functions.py
├── terragrunt.hcl
├── variables.tf
└── version.tf
```
