### ISSUE TITLE
pip_requirements generates invalid JSON

### ISSUE THREAD

**Issue by Nogginboink** [terraform-aws-modules/terraform-aws-lambda#220]
My lambda layer is properly including all of my Python files in my source_path, including requirements.txt, and is properly packaging them to the desired .zip prefix, and is deploying the layer to AWS.

However, when I add a requirements.txt to my layer and enable pip_requirements, terraform throws the error:

```
2021-10-30T14:44:11.451-0500 [INFO]  backend/local: plan operation completed
╷
│ Error: command "python.exe" produced invalid JSON: invalid character 'd' looking for beginning of value
│
│   with module.aws_lambda.data.external.archive_prepare[0],
│   on .terraform\modules\aws_lambda\package.tf line 7, in data "external" "archive_prepare":
│    7: data "external" "archive_prepare" {
```

My module code is:
```
module "aws_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 2.0"

  create_function     = false
  create_layer        = true
  layer_name          = join("_", [local.app_name, "test_lambdabaselayer"])
  description         = "Low level functions used by many lambda functions"
  compatible_runtimes = [local.python_runtime]
  runtime             = local.python_runtime
  source_path = [
    { path             = "../lambdas/base_layer2"
      pip_requirements = true #same error with "../lambdas/base_layer2/requirements.txt"
      prefix_in_zip    = join("/", ["python", "lib", local.python_runtime, "site-packages"])
    }
  ]
}
```

I enabled terraform debugging and see: in the output: 
```
2021-10-30T14:47:06.046-0500 [INFO]  provider.terraform-provider-external_v2.1.0_x5.exe: 2021/10/30 14:47:06 [TRACE] JSON output: doing pip requirements step
{
  "filename": "builds\\bf88d44aa4a0f779d28953c90041f02bf4721227aec1bc8d0479659a0fdd4f2e.zip",
  "build_plan": "{\"filename\": \"builds\\\\bf88d44aa4a0f779d28953c90041f02bf4721227aec1bc8d0479659a0fdd4f2e.zip\", \"runtime\": \"python3.8\", \"artifacts_dir\": \"builds\", \"build_plan\": [[\"pip\", \"python3.8\", \"../lambdas/base_layer2\\\\requirements.txt\", \"python/lib/python3.8/site-packages\"], [\"zip\", \"../lambdas/base_layer2\", \"python/lib/python3.8/site-packages\"]]}",
  "build_plan_filename": "builds\\bf88d44aa4a0f779d28953c90041f02bf4721227aec1bc8d0479659a0fdd4f2e.plan.json",
  "timestamp": "1635623226024893000",
  "was_missing": "true"
: timestamp=2021-10-30T14:47:06.046-0500
```

Can anyone suggest a solution or further troubleshooting?

**Comment by Nogginboink** [comment]
After playing around with this and adding various debug print statements throughout package.py, it seems that an unexpected newline in build_plan is causing the problem; if I copy/paste the output into various online JSON validators, removing the newline causes the JSON to go from invalid to valid.

**Comment by antonbabenko** [comment]
I am afraid you are right, Windows is still a rather peculiar platform when it comes to use for DevOps tasks (and probably this module has some weird issues, too).

Could you please point to the line or function which produces the wrong JSON in `package.py` to help us to identify the issue quicker?

**Comment by Nogginboink** [comment]
Hm. I'm trying to create a minimum viable repro of the issue and can't get the problem to reproduce in a smaller project. As part of my troubleshooting I deleted and reinstalled the lambda module and now my project is building properly. I have no idea what changed, but this issue should probably be closed "no repro."

**Comment by antonbabenko** [comment]
Good that it works for you now. Let's close it and reopen it if a problem happens to come back.
