### ISSUE TITLE
s3 trigger

### ISSUE THREAD

**Issue by mayaaravotwm** [terraform-aws-modules/terraform-aws-lambda#221]
hey, is there support to have s3 trigger in the module?

**Comment by antonbabenko** [comment]
Hey!

There is another module for setting up S3 bucket notifications that will send events to Lambdas/SQS/SNS/etc. See this example - https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/notification/main.tf#L105-L119

This module defines Lambda-related resources.
