### ISSUE TITLE
Allow build_in_docker to work with non-Python runtimes.

### ISSUE THREAD

**Issue by andredigenova** [terraform-aws-modules/terraform-aws-lambda#223]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
I am deploying Lambdas with the NodeJS runtime and would like this Terraform module to build the dependencies through "npm install" within a Docker container to ensure compatibility with natively built modules.

This could be through having the "build_in_docker" option respected by a source_path specified like this: 

source_path = [
    {
      path = "../../src",
      commands = [
        "npm install",
        ":zip"
      ]
    }
  ]

or via a custom thing like the pip_requirements.

## Describe alternatives you've considered.
Manually building out a pipeline to run npm install.

## Additional context

**Comment by antonbabenko** [comment]
Python is needed for the Terraform module to work (no matter if Lambda runtime is Python or JS). This is a hard requirement for this module at the moment as long as `create_package` is `true`.

A good practice (or a rule of thumb) for this module, is to use existing building&packaging features if they work for your case, and look into building docker images (eg. using [docker-build module](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/modules/docker-build)) or even build externally, as soon as standard capabilities are not sufficient for the use-case. See this [example](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/examples/container-image).

I am going to close this issue as there is nothing we can do.
