### ISSUE TITLE
apply completes successfully even though CodeDeploy fails

### ISSUE THREAD

**Issue by wgiddens** [terraform-aws-modules/terraform-aws-lambda#224]
We're testing the deploy module with `wait_deployment_completion = true`.  We're also setting `before_allow_traffic_hook_arn` to do some work before the alias flips to the new version. 

If the deployment or beforeAllowTrafficHook fails, the script finishes with a 0 exit code.  Terraform thinks all is well and continues with the deployment.  Terraform normally stops execution and errors out when it fails to apply a change so I would expect the failed CodeDeploy deployment to cause it to fail and error out as well.

A simple fix would be to `exit 1` in the script when the deployment fails, but others may be relying on the current behavior. It might make sense to add a new var to enable it.

**Comment by antonbabenko** [comment]
Hi Will,

I am not sure I understand where exactly do you want to add `exit 1` in the script.

Could you please explain with some code snippets?

**Comment by wgiddens** [comment]
I opened a pull request to show the location.
