### ISSUE TITLE
deploy module should grant invoke permission to code deploy hooks 

### ISSUE THREAD

**Issue by wgiddens** [terraform-aws-modules/terraform-aws-lambda#226]
The deploy module has a var for `before_allow_traffic_hook_arn` and `after_allow_traffic_hook_arn` where you can set the arn of a Lambda function for CodeDeploy to call during the deployment. However, the role created by `create_codedeploy_role` doesn't grant permission for CodeDeploy to invoke the before or after hooks.

The role should add the InvokeFunction permissions for the hooks if they are set and `create_codedeploy_role` is true.

**Comment by antonbabenko** [comment]
Hi! Could you please make a PR and show it in code (it is much easier and faster for me to understand)?
