### ISSUE TITLE
How to reference Lambda ARN in provided statements

### ISSUE THREAD

**Issue by adamantike** [terraform-aws-modules/terraform-aws-lambda#229]
## Is your request related to a problem? Please describe.

There are some scenarios where the policy statements associated with a Lambda function role need to reference that same Lambda function ARN. An example is **Lambda secret rotation functions**, where the [AWS documentation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-required-permissions-function.html#rotating_execution-role-policy) specifies that the Lambda function role needs to include a policy statement like the following one:
```json
{
	"Effect": "Allow",
	"Action": [
		"secretsmanager:DescribeSecret",
		"secretsmanager:GetSecretValue",
		"secretsmanager:PutSecretValue",
		"secretsmanager:UpdateSecretVersionStage"
	],
	"Resource": "SecretARN",
	"Condition": {
		"StringEquals": {
			"secretsmanager:resource/AllowRotationLambdaArn": "<LambdaRotationFunctionARN>",
			"aws:SourceAccount": "111122223333"
		}
	}
}
```

## Describe the solution you'd like.
A simple approach I have been using in simpler Lambda TF modules is to have a keyword (e.g. `"self"`) that can be provided in the `condition.values` list, to indicate the Lambda function ARN must be populated there:
```hcl
dynamic "statement" {
	# ...
	dynamic "condition" {
		for_each = lookup(statement.value, "condition", [])
		content {
			test     = condition.value.test
			variable = condition.value.variable
			values   = (
				condition.value.values != null
				? [for value in condition.value.values : value == "self" ? aws_lambda_function.this[0].arn : value]
				: condition.value.values
			)
		}
	}
}
```

This would be the first reference to `aws_lambda_function.this[0]` from `iam.tf`, which I'm not sure we were trying to avoid altogether.

## Describe alternatives you've considered.
The current alternative right now has been to attach this kind of policies outside of the module call, duplicating part of the logic already included in this module.

**Comment by antonbabenko** [comment]
Hi Michael,

Yes, very good idea. I never had enough need to make it as part of this module. :)

Two things I propose:
1. Let's use something more descriptive that does not look like a value itself. Let's use `"AWS_LAMBDA_FUNCTION_ARN"` instead of `"self"`.
2. The value potentially can be used as a prefix for some conditions (e.g. `arn` + `:` + `123`, where `123` is the version), so it is safer to use `replace()` like this:

```hcl
values =  try([ for v in condition.value.values: replace(v, "AWS_LAMBDA_FUNCTION_ARN", aws_lambda_function.this[0].arn) ], condition.value.values)
```

Will you be able to make a PR for this (also update the complete example to show this in action, and README)?

**Comment by adamantike** [comment]
That's a really clean solution, thanks for the improved implementation!

I can definitely work on this one, and have the PR ready as soon as possible. I'll try to create a new example too, specific to Lambda rotation functions.
