### ISSUE TITLE
Timeout limit should be removed

### ISSUE THREAD

**Issue by zfanta** [terraform-aws-modules/terraform-aws-lambda#231]
## Is your request related to a problem? Please describe.

Function timeout of origin request and origin response events is 30 seconds at [Quotas on Lambda@Edge](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge). But in [this line of code](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v2.25.0/main.tf#L30), it limits the timeout using `min(var.timeout, 5)`

## Describe the solution you'd like.

Remove `min(var.timeout, 5)`

**Comment by antonbabenko** [comment]
Good point! Instead of removing the value, we can change it from `5` to `30`. It will be better than now at least.

**Comment by antonbabenko** [comment]
[v2.26.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.26.0) has been just released.
