### ISSUE TITLE
maximum_retry_attempts does not work

### ISSUE THREAD

**Issue by imagekitio** [terraform-aws-modules/terraform-aws-lambda#239]
## Description

Changing values of `maximum_retry_attempts` has no impact and `terraform plan` or `terraform apply` does not see it as a change.

## ⚠️ Note

Before you submit an issue, please perform the following first:

- [x] Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
- [x] Re-initialize the project root to pull down modules: `terraform init`
- [x] Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform: v1.0.7
 - Provider(s): terraform-aws-modules/lambda/aws version `2.28.0`

 - Module:
```
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/external v2.1.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

## Reproduction
- Create a lambda function using [this example with vpc](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v2.28.0/examples/with-vpc/main.tf).
- Now edit `main.tf` and set value for `maximum_retry_attempts`.
- Run `terraform plan`, it should show some change, however, it will say that the infrastructure matches the configuration which is not true because the default value of retry attempts is `2` and it can be seen in the AWS console.

## Expected behavior
`terraform plan` should pick up the changes.

## Actual behavior
`terraform plan` should pick up the changes if the value of `maximum_retry_attempts` is changed.

**Comment by christiangeiger-bayer** [comment]
The issue still exists. Please reopen it.

**Comment by antonbabenko** [comment]
The [VPC example](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/with-vpc/main.tf) mentioned in the issue has nothing to do with the `maximum_retry_attempts` and async events.

You can try to run [examples/async](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/async/main.tf#L30) where changes to `maximum_retry_attempts` are tracking correctly.
