### ISSUE TITLE
Multiple file_system_config support

### ISSUE THREAD

**Issue by frankyhun** [terraform-aws-modules/terraform-aws-lambda#248]
## Is your request related to a new offering from AWS?
yes

## Is your request related to a problem? Please describe.
Wanted to use it with two mounted EFS access points

## Describe the solution you'd like.
Multiple EFS access points should be possible to pass to the module, preferably as a list

## Describe alternatives you've considered.
-

**Comment by antonbabenko** [comment]
I don't think it is supported by AWS, so we can't do anything here.
