### ISSUE TITLE
S3 Object Put fails when tags map contains more than 10 tags

### ISSUE THREAD

**Issue by kbrockhoff** [terraform-aws-modules/terraform-aws-lambda#249]
## Description

Many enterprises have an extensive list of required tags. This can cause a failure when applying `aws_s3_bucket_object.lambda_package` because S3 Objects are limited to 10 tags. All other resources created by the module are provisioned without error because of higher maximum tag limits.

Module needs to provide a flag for not merging `tags` with  `s3_object_tags` to avoid a put failure while still complying with the organization's tagging requirements.

## Versions
 - Terraform: v1.0.11
 - Provider(s): HashiCorp/aws v3.69,0
 - Module: v2.28.0

## Reproduction

1. Set tags variable with a map of more than 10 key-value pairs.
2. Don't set value for s3_object_tags so it uses the default of {}. 
3. Execute terraform apply.

### Code Snippet to Reproduce
```
tags = {
  tag1  = "value1"
  tag2  = "value2"
  tag3  = "value3"
  tag4  = "value4"
  tag5  = "value5"
  tag6  = "value6"
  tag7  = "value7"
  tag8  = "value8"
  tag9  = "value9"
  tag10 = "value10"
  tag11 = "value11"
}
```
## Expected behavior
S3 Object put of lambda package should succeed.

## Actual behavior
Put fails with too many tags message.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.32.0 :tada:
