### ISSUE TITLE
Module crashes when create set to false

### ISSUE THREAD

**Issue by kbrockhoff** [terraform-aws-modules/terraform-aws-lambda#251]
## Description

If module is used within a larger Terraform stack and create is set to false to disable, then all Terraform plan and apply operations on the parent stack fail with:

Error: Invalid function argument
│
│   on ../../main.tf line 14, in locals:
│   14:   s3_key            = var.s3_existing_package != null ? lookup(var.s3_existing_package, "key", null) : (var.store_on_s3 ? var.s3_prefix != null ? format("%s%s", var.s3_prefix, replace(local.archive_filename, "/^.*//", "")) : replace(local.archive_filename, "/^\\.//", "") : null)
│     ├────────────────
│     │ local.archive_filename is null
│
│ Invalid value for "str" parameter: argument must not be null.

## Versions
 - Terraform: v1.0.11
 - Provider(s): hashicorp/aws v3.39.0
 - Module: v2.28.0

## Reproduction
1. Set create = false
2. terraform plan

### Code Snippet to Reproduce
  create = false

## Expected behavior
Terraform plan or apply should succeed with no op on resources defined by the module.

## Actual behavior
Terraform plan or apply fails with error.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.33.1 :tada:

**Comment by antonbabenko** [comment]
This bug was present only when S3 configuration was specified (e.g. `store_on_s3 = true`). Thank you for reporting it and opening a PR!
