### ISSUE TITLE
Accept "function_response_types" in event_source_mapping

### ISSUE THREAD

**Issue by keng000** [terraform-aws-modules/terraform-aws-lambda#254]
## Is your request related to a new offering from AWS?

Yes.
It is about a new feature "partial batch response" which allows to partially make it succeed and partially make it fail when using Lambda with SQS event source trigger.
https://aws.amazon.com/about-aws/whats-new/2021/11/aws-lambda-partial-batch-response-sqs-event-source/

And it is also supported by the AWS provider.
To enable this feature, the new argument `function_response_types` in `aws_lambda_event_source_mapping` has to be setted.

## Describe the solution you'd like.

I suggest adding a new optional configuration in `aws_lambda_event_source_mapping` to accept the new argument `function_response_types` which will configure as I describe above.

(Update) I created a PR for this. https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/255

**Comment by antonbabenko** [comment]
Fixed in #255.
