### ISSUE TITLE
ResourceConflictException: concurrent updates during Lambda creation

### ISSUE THREAD

**Issue by riy** [terraform-aws-modules/terraform-aws-lambda#263]
## Description

The `resource "aws_lambda_function_event_invoke_config" "this"` gets fired twice, in quick and consecutive order, and, for our setup, leads to issues with concurrent updates on the Lambda.

Spoiler alert: we found out what the issue is and found a workaround.

## Versions
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

 - Module: `terraform-aws-modules/lambda/aws`

## Reproduction
1. We have a `main.tf` that makes calls to the same (custom) module, three times.
2. Our custom module calls `terraform-aws-modules/lambda/aws` and configures it with `create_async_event_config = true`, which is sufficient for the defaults in the `variables.tf` to come into play and trigger a call of `aws_lambda_function_event_invoke_config`.
3. This resource, `aws_lambda_function_event_invoke_config`, will use `locals.qualifiers` to make two calls via a `for_each`, in quick succession, once for `current_version` and once for `unqualified_alias`.
4. This leads to the following error message, printed:
```terraform
│ Error: error putting Lambda Function Event Invoke Config (tracking-enrichment-stage-search-enriched-to-aurora:$LATEST): ResourceConflictException: The EventInvokeConfig for function arn:aws:lambda:eu-central-1:<ACCOUNT_ID>:function:tracking-enrichment-stage-search-enriched-to-aurora:$LATEST could not be updated due to a concurrent update operation.
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "6768fc9b-15b2-4fc2-ab60-bbb836d617d4"
│   },
│   Message_: "The EventInvokeConfig for function arn:aws:lambda:eu-central-1:<ACCOUNT_ID>:function:tracking-enrichment-stage-search-enriched-to-aurora:$LATEST could not be updated due to a concurrent update operation.",
│   Type: "User"
│ }
│
│   with module.search_enriched_to_aurora.module.lambda_enriched_to_aurora.aws_lambda_function_event_invoke_config.this["current_version"],
│   on .terraform/modules/search_enriched_to_aurora.lambda_enriched_to_aurora/main.tf line 166, in resource "aws_lambda_function_event_invoke_config" "this":
│  166: resource "aws_lambda_function_event_invoke_config" "this" {
```
5. Right before the above error is shown this is printed, which also shows that this is related to `aws_lambda_function_event_invoke_config`:
```terraform
module.search_enriched_to_aurora.module.lambda_enriched_to_aurora.null_resource.delay: Creation complete after 3m0s [id=9041741638196074955]
module.search_enriched_to_aurora.module.lambda_enriched_to_aurora.aws_lambda_function_event_invoke_config.this["unqualified_alias"]: Creating...
module.search_enriched_to_aurora.module.lambda_enriched_to_aurora.aws_lambda_function_event_invoke_config.this["current_version"]: Creating...
module.search_enriched_to_aurora.module.lambda_enriched_to_aurora.aws_lambda_function_event_invoke_config.this["unqualified_alias"]: Creation complete after 0s [id=tracking-enrichment-stage-search-enriched-to-aurora]
```

## Expected behavior
The calls should be made in an order that doesn't cause concurrent updates.

## Actual behavior
The same Lambda is modified twice, at the same time.

## Workaround

The following is a VERY quick and dirty workaround that is NOT worthy of a pull request (hence I didn't create one), but worked for us in our very specific (!) use case to make this go away quickly.  
We're basically calling `aws_lambda_function_event_invoke_config` twice (instead of just once), with the first one just for `current_version`, and the second one for `unqualified_alias`, which then `depends_on` the first one to being fully created.  

The yellow rectangles show the relevant changes and additions, whereas you should know that the second call to `aws_lambda_function_event_invoke_config` was not there before.

![image](https://user-images.githubusercontent.com/903321/152053201-5034790c-8391-49dc-ae3f-61b08c78ed82.png)

It would be awesome if someone with a deeper understanding of this module could have another look and maybe issue a proper pull request that fixes this issue. Alternatively, as the best solution, this could also be solved via the AWS provider, or the AWS API, but I guess it'd take them way too long to address, acknowledge and fix this issue there.

**Comment by antonbabenko** [comment]
Thank you for opening this issue. It is always tricky to tell Terraform to create resources sequentially as you need here.

I currently can't imagine a better solution than the one you're proposing, so please make a PR and make sure that you update the code in the `examples/alias` to show this behavior fully.

**Comment by riy** [comment]
Thank you for the quick response, @antonbabenko.

I was hoping there'd be some trick that would let us have a single `resource` call instead of two, but if you say this is probably the best way to implement this then I'll issue a pull request shortly.
Also, thanks for the hint on `examples/alias`, I'll make sure I look into that as well.

**Comment by antonbabenko** [comment]
You are welcome! `examples/alias` and `examples/async` should be reviewed and updated.
