### ISSUE TITLE
Support for updating aws_lambda_provisioned_concurrency_config but for Alias's

### ISSUE THREAD

**Issue by seb-moviestarplanet** [terraform-aws-modules/terraform-aws-lambda#264]
## Is your request related to a new offering from AWS?
This feature has been available to lambda_function resource since 2.41.0 version of AWS provider.

https://registry.terraform.io/providers/hashicorp/aws/2.41.0/docs/resources/lambda_provisioned_concurrency_config

## Is your request related to a problem? Please describe.
Yes, I can't update my Lambda Alias's provisioned concurrency 

## Describe the solution you'd like.
Instead of having one input for concurrency then have two, e.g. like this "provisioned_concurrent_executions_version" "provisioned_concurrent_executions_alias"

## Describe alternatives you've considered.
Currently I have to manage this through the AWS console

**Comment by seb-moviestarplanet** [comment]
Hi Anton, thank you for your quick response, forgive me if I'm wrong but the example you've provided will set the provisioned concurrency for the lambda version and not the alias.

**Comment by antonbabenko** [comment]
You are right that this module does not set provisioned concurrency for an alias.

If I remember correctly now, there were some bugs that prevented me from adding it to the module. For e.g. https://github.com/hashicorp/terraform-provider-aws/issues/13329 and [more](https://github.com/hashicorp/terraform-provider-aws/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+aws_lambda_provisioned_concurrency_config).

If there is a good workaround for this problem, pull request to `modules/alias` and [examples/alias](https://github.com/terraform-aws-modules/terraform-aws-lambda/tree/master/examples/alias) is welcome. :)
