### ISSUE TITLE
Create Cloudwatch log groups for Lambda@Edge in each available region

### ISSUE THREAD

**Issue by atsikham** [terraform-aws-modules/terraform-aws-lambda#265]
## Is your request related to a new offering from AWS?
Not new

## Is your request related to a problem? Please describe.
Hi, I found this module during searching for a solution to create Lambda@Edge log groups in each available/enabled region. Unfortunately, I [don't see](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/159f57aede1173a41ab9ef362909f8fb3e67d8d4/main.tf#L143) that this situation is handled.

In addition, [here](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/086013837d18ead0fa84269faa66054b5a63f27f/variables.tf#L329) value '0' is possible but not mentioned. Would be nice to add validation.

## Describe the solution you'd like.
To configure logs retention period, create Cloudwatch log groups for Lambda@Edge in each available region.

## Describe alternatives you've considered.
Manual retention setting.

## Additional context
Some links about that:

AWS:

- https://forums.aws.amazon.com/thread.jspa?messageID=899555&tstart=0
- https://aws.amazon.com/ru/blogs/networking-and-content-delivery/aggregating-lambdaedge-logs/

Terraform:

- https://github.com/hashicorp/terraform/issues/16967
- https://stackoverflow.com/questions/69885339/how-to-deploy-aws-resources-across-all-regions-via-terraform
- https://github.com/hashicorp/terraform/issues/24476
- https://discuss.hashicorp.com/t/provider-registry-registry-terraform-io-does-not-have-a-provider-named-registry-terraform-io-hashicorp-each/21695/4
- https://stackoverflow.com/a/48667361/6701498

**Comment by atsikham** [comment]
Hi @antonbabenko, thanks for the answer. I'm talking about the case when you want a log group(s) to be created by the module (as it has inputs for that), but in fact it will be created in one region. If end users accessed the service from other regions, log group will be automatically created in that regions, but there is no consistency in settings between created log groups by this module and other ones created automatically.

**Comment by antonbabenko** [comment]
Actually, I think you should be able to create log groups outside of the module with the desired retention in each region and Lambda@Edge will be able to write into those and not reset retention.

**Comment by atsikham** [comment]
> Actually, I think you should be able to create log groups outside of the module with the desired retention in each region and Lambda@Edge will be able to write into those and not reset retention.

Yes, it's so, as for different AWS services like RDS, but input variable of this module promises creation of log group and creates it only in one region, that might be unexpected for end user.
