### ISSUE TITLE
Concurrency issues while bundling

### ISSUE THREAD

**Issue by webratz** [terraform-aws-modules/terraform-aws-lambda#266]
## Description
I have a module that contains this lambda module. This is called several times with different parameters (around 15 times).
It works in most cases, but it seems there is a race condition when bundling and cleaning up, so that files are removed before they can be packaged.

I assume its due to terraforms pararellism setting which executes by default 10 things in parallel. Its no option to reduce this, as the overall terraform setup is quite big and the run times would be too long.

It manifests with an error like this during apply.

```
│ Error: local-exec provisioner error
│ 
│   with module.shared.module.my module.module.datadog_cfn_config_lambda.null_resource.archive[0],
│   on .terraform/modules/mymodule.datadog_cfn_config_lambda/package.tf line 65, in resource "null_resource" "archive":
│   65:   provisioner "local-exec" {
│ 
│ Error running command
│ 'builds/5b2aab9279a21f1df29e7e99ba259cdfda8e442af2e23e802cfcfaf2d59bb7ad.plan.json':
│ exit status 1.

.... (just zip files adding output)

│ Traceback (most recent call last):
│   File "/builds/sre/terraform-aws/configuration/master/.terraform/modules/mymodule.datadog_cfn_config_lambda/package.py", line 1273, in <module>
│     main()
│   File "/builds/sre/terraform-aws/configuration/master/.terraform/modules/mymodule.datadog_cfn_config_lambda/package.py", line 1269, in main
│     exit(args.command(args))
│   File "/builds/sre/terraform-aws/configuration/master/.terraform/modules/mymodule.datadog_cfn_config_lambda/package.py", line 1161, in build_command
│     bpm.execute(build_plan, zs, query)
│   File "/builds/sre/terraform-aws/configuration/master/.terraform/modules/mymodule.datadog_cfn_config_lambda/package.py", line 318, in __exit__
│     self.close()
│   File "/builds/sre/terraform-aws/configuration/master/.terraform/modules/mymodule.datadog_cfn_config_lambda/package.py", line 308, in close
│     os.replace(self._tmp_filename, self.filename)
│ FileNotFoundError: [Errno 2] No such file or directory:
│ 'builds/5b2aab9279a21f1df29e7e99ba259cdfda8e442af2e23e802cfcfaf2d59bb7ad.zip.tmp'
│ ->
│ 'builds/5b2aab9279a21f1df29e7e99ba259cdfda8e442af2e23e802cfcfaf2d59bb7ad.zip
```

## Versions

 - Terraform:
 ```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/carlpett/sops v0.6.3
+ provider registry.terraform.io/datadog/datadog v3.8.1
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```
 - Module:
```
module "datadog_cfn_config_lambda" {
  source                            = "terraform-aws-modules/lambda/aws"
  version                           = "2.34.0"
  function_name                     = "datadog_cfn_config_lambda"
  cloudwatch_logs_retention_in_days = 7
  handler                           = "handler.handle"
  runtime                           = "python3.9"
  timeout                           = "30"
  memory_size                       = "256"
  publish                           = true
  source_path = [{
    path             = "${path.module}/lambda/datadog-cfn"
    pip_requirements = true
    }
  ]
}
```

## Reproduction
It's generally hard to get that to reproduce consistently. As described above many lambda functions being bundled in parallel seems to trigger that.

### Code Snippet to Reproduce
Will try to build a small demo setup later.

## Expected behavior
The bundling should either not happen in parallel (using a lock) or being able to run in parallel without race conditions.

## Actual behavior
See error description in the beginnging

**Comment by antonbabenko** [comment]
Hi @webratz !

There are multiple things you can do.

I am not sure if you are building the same function 15 times but you can build a package once and then use packaged artifact when you deploy it 15 times.

You can parametrize few things:
1. [artifacts_dir](https://github.com/terraform-aws-modules/terraform-aws-lambda#input_artifacts_dir) - to keep each artifact in a separate subfolder, for example.
2. [hash_extra](https://github.com/terraform-aws-modules/terraform-aws-lambda#input_hash_extra) - to ensure that produced artifacts have different filenames.

There are examples for both of these parameters in the `examples/` folder.

**Comment by webratz** [comment]
Yeah, sadly it currently builds the same function 15 times (its deployed into different accounts) - so this is pretty inefficient.
I will have a look at the two parameters and see if i can work around it.

Thanks for the quick response

**Comment by webratz** [comment]
This seems to have solved my issue. 🎉
