### ISSUE TITLE
"python3": source_path must be set

### ISSUE THREAD

**Issue by Andrey9kin** [terraform-aws-modules/terraform-aws-lambda#27]
Could you please give me a hand with this? 

I'm running on Alpine 3.10, Python 3.7. It works locally (Ubuntu 20.04, Python3.8) but for some reason fails in CI (alpine) and I'm having hard time figuring out in what direction to dig

```
Terraform v0.12.24
+ provider.aws v2.66.0
+ provider.external v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
```

```
module "lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "1.5.0"

  function_name = module.name.qualified_name
  description   = local.description
  handler       = "main.handler"
  runtime       = "python3.8"
  publish       = true

  source_path = "../../src/"
....
```

```
 Error: failed to execute "python3": source_path must be set.
[2020-06-16T12:04:23.320Z] 
 
   on .terraform/modules/lambda/terraform-aws-lambda-1.5.0/package.tf line 3, in data "external" "archive_prepare":
    3: data "external" "archive_prepare" {
```

**Comment by Andrey9kin** [comment]
@antonbabenko is it something you saw before?

**Comment by antonbabenko** [comment]
Sure, first, make sure that you use latest version of the module where more under-the-hood improvements and bugfixes were made.

Your error message means that `source_path` is wrong. You can write it like this:
```
source_path = "${path.module}/../../src/"
```

or try to use absolute path.

**Comment by antonbabenko** [comment]
Also, it should work on Python 3.6 as you mentioned another day :)

**Comment by Andrey9kin** [comment]
@antonbabenko thanks for suggestions!

```
source_path = "${path.module}/../../src/"
```
^ was the first thing I tried. It didn't work so I thought to change it to how it shown in examples but didn't help either. Thus I'm here. Is there anything else to try to debug it?

**Comment by antonbabenko** [comment]
Have you tried to use an absolute path?

**Comment by antonbabenko** [comment]
If you would use terragrunt, you should use this hack:
```
source_path = jsonencode("${path.module}/../../src/")
```

Ref: https://github.com/gruntwork-io/terragrunt/issues/1211

**Comment by Andrey9kin** [comment]
Even if it works it is not usable since the absolute path will be different in CI and locally. But I'm going to give it a try. No plane terraform wrapped into a little bit of shell

**Comment by antonbabenko** [comment]
You can enable debug as described in README.
```
export TF_LAMBDA_PACKAGE_LOG_LEVEL=DEBUG2
terraform apply
```

A little bit of shell... can be related to the bug linked above. Wrap it with `jsonencode()`.

**Comment by Andrey9kin** [comment]
@antonbabenko weird, but I'm getting the same results as for jsonencode as for absolute path

do I read it right that error message 

```
failed to execute "python3": source_path must be set.
```
comes from package.py, i.e. it is python script complaining about source_path, not terraform, right?

**Comment by Andrey9kin** [comment]
Ok, it is from here

```
    # Validate the query.
    if not os.path.exists(source_path):
        abort('source_path must be set.')
```
I would suggest changing the message to something that actually describes what is going on - here the program checks that path it got points to something that exists. So a better message would be to display the content of the variable and tell the user that it does not exist. Then user will be able to act on it. Right, now it is somewhat misguiding. Going to experiment with the code a little bit

**Comment by Andrey9kin** [comment]
@antonbabenko 🤦 forgot to commit src; that is why it works locally and not it CI. Kind of obviously. Anyhow, going to send a pull request to improve the message

**Comment by Andrey9kin** [comment]
Nevermind, that code already got changed in the latest version. Then no pull request. Thanks for your help!

**Comment by antonbabenko** [comment]
Thanks! Good luck :)

PS: No automation = no need to commit anything anywhere = works on my machine 100% :trollface:
