### ISSUE TITLE
Allow selection of provider

### ISSUE THREAD

**Issue by Nogginboink** [terraform-aws-modules/terraform-aws-lambda#270]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
My Terraform stack has several AWS providers specified (with aliases): aws.primary-region, aws.secondary-region, etc. For AWS Terraform resources, I can specify a 'provider' parameter in the resource block to tell Terraform which provider to use to build the resource. There appears to be no such functionality with terraform-aws-lambda.

## Describe the solution you'd like.
Allow me to specify 'provider' just like I would with any AWS resource in Terraform

## Describe alternatives you've considered.
I could have a default AWS provider, I suppose, or could manually specify the region, but both of those would break the cleanliness of my larger project. Not having a default provider in my Terraform stack ensures that I think through what I'm doing and don't do things by default or by accident and I would like to keep that philosophy.

**Comment by antonbabenko** [comment]
You should pass provider into the module as described here - https://www.terraform.io/language/meta-arguments/module-providers#the-module-providers-meta-argument

There is nothing extra that module should be doing.

**Comment by Nogginboink** [comment]
Thank you! I appreciate the pointer; it did indeed give me what I needed.
