### ISSUE TITLE
Lambda update layer version when managed externally when I expected to ignore it

### ISSUE THREAD

**Issue by lays147** [terraform-aws-modules/terraform-aws-lambda#273]
## Description

Hi, I'm using this module to set up a lambda function and layer. The lambda and layer are updated in a separated pipeline. However, when running terraform pipeline again, the plan changes the lambda layer version back to the version in the terraform state, and I would like to ignore changes in the layer version. How does one do that? I know that can be done using lifecycle rules, but as I can't set it dynamically. Is there a workaround for this?

## Versions

 - Terraform: 1.1.4

 - Provider(s): 
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.2
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

 - Module:
  "v2.34.0"

## Reproduction

1. Create a lambda layer
2. Create a lambda function
3. Run terraform plan & apply
3. Update lambda layer version externally
4. Update lambda function to use new lambda layer
5. Run terraform plan
6. The plan changes the lambda layer version to the one registered on the state

### Code Snippet to Reproduce
```hcl
module "lambda" {
  source                            = "terraform-aws-modules/lambda/aws"
  version                           = "v2.34.0"
  attach_policies                   = true
  cloudwatch_logs_retention_in_days = local.log_retention_days
  cloudwatch_logs_tags              = local.tags
  create_package                    = false
  function_name                     = local.project
  handler                           = local.handler
  ignore_source_code_hash           = true
  local_existing_package            = data.archive_file.dummy.output_path
  memory_size                       = local.lambda_memory
  runtime                           = "python3.9"
  number_of_policies                = 2
  policies = [
    aws_iam_policy.write_bucket.arn,
    aws_iam_policy.read_dynamo.arn
  ]
  publish               = true
  tags                  = local.tags
  environment_variables = { for env in local.environment : env.name => env.value }
  layers = [
    module.lambda_layer.lambda_layer_arn
  ]
}

module "lambda_layer" {
  source       = "terraform-aws-modules/lambda/aws"
  version      = "v2.34.0"
  create_layer = true

  layer_name               = "${local.project}-layer"
  compatible_runtimes      = ["python3.8", "python3.9"]
  compatible_architectures = ["x86_64"]
  create_package           = false
  ignore_source_code_hash  = true
  local_existing_package   = data.archive_file.dummy.output_path
}

```

## Expected behavior
Lambda layer version in function is ignored.

## Actual behavior
Lambda layer in function is changed back to the version in the state.

### Terminal Output Screenshot(s)

In this case, I need my lambda to use the version 3 of the layer instead of the 4. And as you can see
![image](https://user-images.githubusercontent.com/7799231/155343183-830c15ba-462c-46f3-9b9e-c6f45329150b.png)

**Comment by antonbabenko** [comment]
Hi @lays147 !

You can use data-source [aws_lambda_layer_version](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_layer_version) to get latest available version and pass it to a function instead of:
```
layers = [
    module.lambda_layer.lambda_layer_arn
]
```

It is the only solution that comes to my mind since you are using different pipelines for layer and for function.
