### ISSUE TITLE
Does this want to be a nullable string?

### ISSUE THREAD

**Issue by colvint** [terraform-aws-modules/terraform-aws-lambda#274]
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/a5c03fef2c5c332dc31b84030cbb63302ef8a23d/variables.tf#L324

Would seem like a somewhat more elegant API to be able to pass the name of a log group there. Currently, it takes a `bool` and assumes the module should be in charge of determining the name. A looser coupling could be achieved by passing a `string` there?

**Comment by antonbabenko** [comment]
Lambda function name should be named like `/aws/lambda/<function name>`. User can't give any other name to a log group.

https://docs.aws.amazon.com/lambda/latest/dg/monitoring-cloudwatchlogs.html

**Comment by colvint** [comment]
Yes, found that out the hard way. Fair enough — thanks for the reply!
