### ISSUE TITLE
Request For Tag Enablement

### ISSUE THREAD

**Issue by sandeepgopi** [terraform-aws-modules/terraform-aws-lambda#276]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

When we began using the repo, we found that one of the resources is yet to be tag enabled. Hence when our internal projects were calling this repo, our custom tags were not being added in AWS. Please can you enable tags for the below.

Resource (In the 'terraform-aws-lambda -> modules -> docker-build -> main.tf' file): "aws_ecr_repository"
Resource name: "this"

Description : Request you to implement a map(string) variable called tags and ensure this is implemented for:
The ''aws_ecr_repository" resource with 'this' resource name

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

**Comment by sandeepgopi** [comment]
Hi Authors. Please can you give us an update.
If you are busy, I can make the tag enablement change and raise a Merge request for you to review :)

Thank You 


Kind Regards
Sandeep

**Comment by sandeepgopi** [comment]
up

**Comment by antonbabenko** [comment]
Hi @sandeepgopi !

I have already answered on your PR a few days ago - https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/302#pullrequestreview-939173438

There is nothing we can/should be doing in regards to tag enablement.
