### ISSUE TITLE
Support keep_remotely variables

### ISSUE THREAD

**Issue by michaelhelmick** [terraform-aws-modules/terraform-aws-lambda#283]
## Is your request related to a new offering from AWS?
No.

## Is your request related to a problem? Please describe.
[(https://github.com/kreuzwerker/terraform-provider-docker/issues/358)](https://github.com/kreuzwerker/terraform-provider-docker/issues/358)

Allowing `keep_remotely` on `docker_registry_image` resolves to attempted delete.

## Describe the solution you'd like.

- Add `keep_remotely` support

## Describe alternatives you've considered.

None. This should be supported anyways. (Default false to avoid Major change)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.35.1 :tada:
