### ISSUE TITLE
max_session_duration parameter for aws_iam_role

### ISSUE THREAD

**Issue by avysotsk** [terraform-aws-modules/terraform-aws-lambda#285]
Could you please add max_session_duration parameter to the role created for lambda function. 
The default value is 3600 and sometimes it is required to have more. For instance when the lambda function is used to generate pre-signed S3 URLs which should live longer then one hour.

**Comment by antonbabenko** [comment]
Lambda function assumes that IAM role every time it is executed. The maximum duration of Lambda function execution is 15 minutes, so there is no need to set it to anything more than that really.

**Comment by avysotsk** [comment]
:-) 
Probably too fast?
Imagine the backend lambda function return something like this 
return s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': 'bucket-name',
        'Key': 'key-name'
    },
    ExpiresIn=43200
) 

And frontend  app uses this S3 pre-signed url. When the url will expire? 12 hours(==43200)? No it will expire in one hour, because lambda uses temporary credentials from the role which was created with default value of max_session_duration parameter(3600 sec).

**Comment by antonbabenko** [comment]
If you need to have it for more than an hour, there are these options:
> ### Presigned URLs limitations
> Validity period will vary given you created your presigned URL with:
> 1. IAM instance profile (Valid up to 6 hours)
> 2. AWS Security Token Service (Valid up to 36 hours)
> 3. or with IAM user (Valid up to 7 days with AWS Signature Version 4).

From https://howtocloud.io/generate-s3-presigned-urls-with-boto3/

**Comment by avysotsk** [comment]
Yes. Exactly the second item "AWS Security Token Service" I need to have :-) via temporary security credentials from the role lambda assumed.
