### ISSUE TITLE
Package script fails when using the same source for multiple lambdas

### ISSUE THREAD

**Issue by glenthomas** [terraform-aws-modules/terraform-aws-lambda#288]
## Description

I am using the terraform-aws-lambda module to package and deploy multiple lambda functions in the same terraform module. Each lambda function uses the same source folder, but invokes a different handler function within that folder.

During deployment the Terraform fails with this error (I have trimmed off some of the noise):

```
│ Error: local-exec provisioner error
│ 
│   with module.all_hubs.module.lambda_function.null_resource.archive[0],
│   on .terraform/modules/lambda_function/package.tf line 65, in resource "null_resource" "archive":
│   65:   provisioner "local-exec" {
│ 
│ Error running command
│ 'builds/c66a705cdfe83c388f674cf272553051641352f7de6e5d838f25025eed9b2f6b.plan.json':
│ exit status 1. Output: windows.py
│ zip: adding: ...
│ Traceback (most recent call last):
│   File "/builds/.../package.py", line 1273, in <module>
│     main()
│   File "/builds/.../package.py", line 1269, in main
│     exit(args.command(args))
│   File "/builds/.../package.py", line 1161, in build_command
│     bpm.execute(build_plan, zs, query)
│   File "/builds/.../package.py", line 318, in __exit__
│     self.close()
│   File "/builds/.../package.py", line 308, in close
│     os.replace(self._tmp_filename, self.filename)
│ FileNotFoundError: [Errno 2] No such file or directory:
│ 'builds/c66a705cdfe83c388f674cf272553051641352f7de6e5d838f25025eed9b2f6b.zip.tmp'
│ ->
│ 'builds/c66a705cdfe83c388f674cf272553051641352f7de6e5d838f25025eed9b2f6b.zip'
```

The filename for the zip temp file seems to be the same for each instance of my lambda function so I think one is renaming the package before the others get to use it. Is the filename a hash of the source?

## Versions

 - Terraform: 1.1.7

 - Provider(s): aws 3.75.0

 - Module: 2.35.1

## Reproduction

Multiple instances of the module with the same `source_path`

## Expected behavior

Each lambda function is packaged and deployed successfully.

## Actual behavior

See error above

**Comment by antonbabenko** [comment]
You need to change some arguments in each module block as I described here - https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/266#issuecomment-1033695233

**Comment by glenthomas** [comment]
Thanks @antonbabenko. That is an effective workaround, but would be good if each zipped package could have a unique filename to avoid this. I appreciate that it does not make sense to build the same package more than once.

**Comment by antonbabenko** [comment]
If the content of the package does not change then they will be trying to create the same package thus making problem you are experiencing in the first place. You can create one lambda using `terraform apply -target=modules.lambda_first` and then run `terraform apply` to create the rest and it should pick up the initial package and deploy it.

In your case, I guess, it is easier to create distinct packages using `hash_extra` or [build a package](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/build-package/main.tf) once and deploy it in all functions using `local_existing_package` (see [example](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/complete/main.tf#L154-L179)).
