### ISSUE TITLE
Add ephemeral_storage attribute to Lambda module

### ISSUE THREAD

**Issue by liortct** [terraform-aws-modules/terraform-aws-lambda#290]
## Is your request related to a new offering from AWS?
AWS introduced support for Ephemeral storage size configuration to Lambda functions.

### References
- Announcement: https://aws.amazon.com/about-aws/whats-new/2022/03/aws-lambda-configure-ephemeral-storage/
- API: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-EphemeralStorage
- Blog post: https://aws.amazon.com/blogs/aws/aws-lambda-now-supports-up-to-10-gb-ephemeral-storage/

The new feature is currently in PR in the AWS provider for Terraform - https://github.com/hashicorp/terraform-provider-aws/pull/23873, the new feature will be added to Terraform after the following PR is merged.

## Describe the solution you'd like.
Add a new field named "ephemeral_storage" that will configure the lambda function `ephemeral_storage`.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.37.0 :tada:

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.37.0 :tada:

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.0.0 :tada:
