### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by shyamvala** [terraform-aws-modules/terraform-aws-lambda#297]
## Description

Suddenly the builds started breaking today with error:
`Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints >= 2.53.0, >= 3.24.0, ~> 3.69, >= 4.8.0`

I checked the previous build that succeeded and it didn't have 4.8.0 match. Wondering if this has to do with a commit I saw on this repo related to it. 

Any direction to get out of it will help. Thank you.

## Versions

 - Terraform: 1.0.11

 - Provider(s): AWS

 - Module:

**Comment by antonbabenko** [comment]
Make sure that you are using version 3.0.0 (or newer) with AWS provider version 4, or version `2.x` of the module with AWS provider version 3.

**Comment by shyamvala** [comment]
Thank you sir. I didnt realize we didnt lock the version to 2.x. All good now by using 2.36.0.
