### ISSUE TITLE
Warning: Argument is deprecated

### ISSUE THREAD

**Issue by marujageek** [terraform-aws-modules/terraform-aws-lambda#298]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

![image](https://user-images.githubusercontent.com/16272327/161022121-c3446067-448f-40e7-af7d-aaaf4e43b039.png)

With the provider aws version 4.7.0 and terraform version 1.1.2

**Comment by marujageek** [comment]
Hi, thanks for your response. 
my module has yours as source, which is where I think the warning is

```
module "metadata_external_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "2.35.1"
```

**Comment by antonbabenko** [comment]
Right, you need to upgrade it to the version `3.x`.

```
module "metadata_external_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 3.0"

  # ...
}
```
