### ISSUE TITLE
Files copied by docker-build do not have the correct chmod

### ISSUE THREAD

**Issue by Gaelik-git** [terraform-aws-modules/terraform-aws-lambda#301]
## Description

There is a difference in when building docker image using `terraform-aws-modules/lambda/aws//modules/docker-build` vs `docker build` resulting in error at run time

I created this repo to reproduce: https://github.com/Gaelik-git/terraform-docker-build-bug

When inspecting the image build by the module we can see the permission of copied files are `----------`

- [ ✔️ ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Terraform version: v1.1.6
- Provider version(s):
  provider registry.terraform.io/hashicorp/aws v4.8.0
  provider registry.terraform.io/hashicorp/random v3.1.2
  provider registry.terraform.io/kreuzwerker/docker v2.16.0

## Reproduction Code [Required]

https://github.com/Gaelik-git/terraform-docker-build-bug

```
terraform init
terraform plan
terraform apply
```

```
docker build -t lambda-docker-hello-world .
```

I am using https://github.com/wagoodman/dive to inspect the images
![image](https://user-images.githubusercontent.com/22296560/161927199-3ce52cca-9c92-4d4b-ac10-1f5398077c57.png)

Result of `dive lambda-docker-hello-world`
![image](https://user-images.githubusercontent.com/22296560/161927296-de395976-94ae-47f9-8b1e-41b440d4c200.png)

(You can also check by creating a container
`docker run -it --entrypoint="" NAME_OF_THE_IMAGE bash`
`ls -al`

## Expected behavior

Copied files should keep the correct chmod

## Additional context

To avoid the runtime error I have to add some `RUN chmod -R 755 files` in my docker image, considerably increasing its size

**Comment by Gaelik-git** [comment]
Do you have any inputs about this ?

**Comment by antonbabenko** [comment]
Sorry, not yet. I am busy with other things.
