### ISSUE TITLE
ResourceAlreadyExistsException when creating lambda function using "lambda_function_existing_package_from_remote_url"

### ISSUE THREAD

**Issue by tejas619** [terraform-aws-modules/terraform-aws-lambda#303]
## Description

I am trying to create my lambda function using the lambda_function_existing_package_from_remote_url module.
terraform init and terraform plan works completely fine.
However, when I perform terraform apply, I get the following error:

Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/lambda/lambda-test' already exists.

with module.lambda_function_existing_package_from_remote_url.aws_cloudwatch_log_group.lambda[0],
on .terraform/modules/lambda_function_existing_package_from_remote_url/main.tf line 149, in resource "aws_cloudwatch_log_group" "lambda":
149: resource "aws_cloudwatch_log_group" "lambda" {

## Versions

- Module version [Required]:
    3.1.0
- Terraform version:
    1.0.8
- Provider version(s):
    4.8.0

My question is, is there any way I can configure in the lambda_function_existing_package_from_remote_url module to not create the cloudwatch group at all??

**Comment by antonbabenko** [comment]
Try setting `use_existing_cloudwatch_log_group = true`. It will not create resource `aws_cloudwatch_log_group` but use the one you have already created in advance.

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/main.tf#L150

**Comment by tejas619** [comment]
@antonbabenko I tried using the above flag. I think it worked. But now I am getting a different error as below:
Error: error creating Lambda Function (1): ValidationException: 

status code: 400, request id: 1d20392e-b376-4e8c-8669-8178d2054039

Do you have any pointers on this?

**Comment by antonbabenko** [comment]
The code looks good but it all depends on the values you are specifying there.

I see that there were similar errors reported in Terraform AWS provider:
https://github.com/hashicorp/terraform-provider-aws/issues/23310
https://github.com/hashicorp/terraform-provider-aws/issues/13709
https://discuss.hashicorp.com/t/error-creating-lambda-function-validationexception/8192

Try running Terraform with debugging enabled.

**Comment by tejas619** [comment]
These are the values I am trying to send in:
aws_region = "us-west-2"
lambda_file = "raven.py"
lambda_runtime = "python3.9"
lambda_name = "vulnmgmt-test"
memsize = "130"
handler= "raven.lambda_handler"
description = "Raven Lambda Function"

Do you think all these values are correct syntactically?

**Comment by antonbabenko** [comment]
`memsize = 130` looks wrong to me. It should be `between 128 MB and 10,240 MB` with 128 increments (if I remember now). Try `128` or `256`.

https://docs.aws.amazon.com/lambda/latest/operatorguide/computing-power.html

**Comment by tejas619** [comment]
Did not work. I still get ValidationException

**Comment by antonbabenko** [comment]
Then try to [run terraform CLI in debug mode](https://support.hashicorp.com/hc/en-us/articles/360001113727-Enabling-debug-and-trace-run-logs-in-Terraform-CLI-Cloud-or-Enterprise) to identify the cause for this error.

**Comment by tejas619** [comment]
This is the request payload which is getting sent by lambda/CreateFunction ```{"Code":{"ZipFile":"ewogICJlcnJvcnMiIDogWyB7CiAgICAic3RhdHVzIiA6IDQwNCwKICAgICJtZXNzYWdlIiA6ICJGaWxlIG5vdCBmb3VuZC4iCiAgfSBdCn0="},"Description":"Raven Lambda Function","EphemeralStorage":{"Size":512},"FunctionName":"vulnmgmt-test","Handler":"raven.lambda_handler","MemorySize":128,"PackageType":"Zip","Publish":false,"Role":"","Runtime":"python3.9","Timeout":3}```

So it is not able to find the zip file packaged as lambda deployment pacakge.

Where is the module checking for the local_existing_pacakge?
local_existing_package = data.null_data_source.downloaded_package.outputs["filename"] 

I have these other resources defined in my main.tf 

```resource "null_resource" "download_package" {
  triggers = {
    downloaded = local.downloaded
  }

  provisioner "local-exec" {
    command = "curl -L -o ${local.downloaded} ${local.package_url}"
  }
}

data "null_data_source" "downloaded_package" {
  inputs = {
    id       = null_resource.download_package.id
    filename = local.downloaded
  }
}```

**Comment by antonbabenko** [comment]
Here is a complete example - https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2/blob/87c1de5507e3c2518ce81b23e359493cb21eafc8/examples/complete-http/main.tf#L245-L284

Try to run that example.

```
  create_package         = false
  local_existing_package = "/path/to/package.zip"
```

**Comment by tejas619** [comment]
For some reason, the provisioner command "curl ..." does not execute at all when running the code. @antonbabenko Do you know why this might be the case?
I get this error as debug output

evalApplyProvisioners: module.lambda_function_existing_package_from_remote_url.aws_lambda_function.this[0] is tainted, so skipping provisioning
