### ISSUE TITLE
`ephemeral_storage` block breaks on GovCloud

### ISSUE THREAD

**Issue by tanadeau** [terraform-aws-modules/terraform-aws-lambda#304]
## Description
When using the 3.x versions of this module on AWS GovCloud, the required use of the `ephemeral_storage` parameter is the `aws_lambda_function` resource is causing a validation error.

## Versions

- Module version [Required]: 3.1.0

- Terraform version:
`Terraform v1.1.7`
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.8.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/mrparkers/keycloak v3.7.0
```

## Reproduction Code [Required]
Any use of this module with AWS GovCloud.

Any deployment using this module on AWS GovCloud.

## Expected behavior
Deployment with no errors.

## Actual behavior
`InvalidParameterValueException: Ephemeral storage configuration ('ephemeralStorage') is currently not supported. Please remove the ephemeral storage parameter from your request and try again.`

**Comment by antonbabenko** [comment]
Could you include your code (issue template required it)?

**Comment by antonbabenko** [comment]
I get the point even without code. Let me fix it now.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 3.1.1 :tada:

**Comment by antonbabenko** [comment]
Please give it a try with `ephemeral_storage_size = null`. I currently don't have access to govcloud region to try this myself.

**Comment by tanadeau** [comment]
Trying it now. Thanks for the super-quick reply and fix!

**Comment by tanadeau** [comment]
Everything worked. Thanks again!
