### ISSUE TITLE
No such file or directory error installing pip requirements for Python lambda function

### ISSUE THREAD

**Issue by paultipper** [terraform-aws-modules/terraform-aws-lambda#315]
## Description

I’m trying to use the [Terraform AWS Lambda module](https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#build) to configure a Python lambda function. My Terraform files are in an ./infrastructure folder, and my Python source code is in the ./api folder, so I’ve configured the lambda function thus:

```terraform
module "lambda_function" {
  source = "terraform-aws-modules/lambda/aws"

  function_name = "DbStreamLambdaFunction"
  description   = "DynamoDBStream lambda function"
  handler       = "api.lambdas.dbstream.handler"
  runtime       = "python3.8"

  source_path = [
    {
      path = "${path.root}/../api",
      prefix_in_zip    = "api"
    },
    {
      path = "${path.root}/../api",
      pip_requirements = true
    }
  ]

  environment_variables = {
    DEBUGPY_BREAKPOINTS = var.debug_breakpoints
    BUCKET_NAME = module.buckets.bucket_name
  }

  tags = {
    Name = "DynamoDBStream lambda function"
  }

  timeout = 60
}
```

The `tflocal plan` command completes successfully, but when I try to execute the tflocal apply command, I get the following error:

```bash
zip: adding: api/utils/__pycache__/debugby_listener.cpython-38.pyc
zip: adding: api/utils/__pycache__/generic_utils.cpython-310.pyc
zip: adding: api/utils/__pycache__/generic_utils.cpython-38.pyc
Installing python requirements: ./../api/requirements.txt
> mktemp -d terraform-aws-lambda-XXXXXXXX # /var/folders/w3/gpkv45ps72sdkjcdgpbxdg65hdytbc/T/terraform-aws-lambda-y2lez1qc
> cd /var/folders/w3/gpkv45ps72sdkjcdgpbxdg65hdytbc/T/terraform-aws-lambda-y2lez1qc
> python3.8 -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt
Processing /home/ktietz/src/ci/alabaster_1611921544520/work
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:
'/System/Volumes/Data/home/ktietz/src/ci/alabaster_1611921544520/work'

zip: Error during zip archive creation
Traceback (most recent call last):
  File "/Users/ac8dqzz/Documents/Development/DSC/spinning-jenny/spinningjenny-backend/infrastructure/.terraform/modules/tables.lambda_function/package.py", line 1277, in build_command
    bpm.execute(build_plan, zs, query)
  File "/Users/ac8dqzz/Documents/Development/DSC/spinning-jenny/spinningjenny-backend/infrastructure/.terraform/modules/tables.lambda_function/package.py", line 811, in execute
    with install_pip_requirements(query, pip_requirements, tmp_dir) as rd:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/ac8dqzz/Documents/Development/DSC/spinning-jenny/spinningjenny-backend/infrastructure/.terraform/modules/tables.lambda_function/package.py", line 958, in install_pip_requirements
    check_call(pip_command, env=subproc_env)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python3.8', '-m', 'pip', 'install', '--no-compile', '--prefix=', '--target=.', '--requirement=requirements.txt']'
returned non-zero exit status 1.
```

I definitely have a requirements.txt file in my ${workspaceFolder}/api folder.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: v3.2.1

- Terraform version: v1.1.9

## Reproduction Code [Required]

1. cd into the `infrastructure` sub-directory.
2. Run the `tflocal plan` command (tflocal is wrapper around terraform to deploy the stack to a LocalStack instance). The command completes successfully.
3. Run the `tflocal apply` command - the error described above is displayed.

## Expected behavior

The `tflocal apply` command should complete successfully and the infrastructure should be deployed to the LocalStack instance.

## Actual behavior

The error described above is displayed.

**Comment by antonbabenko** [comment]
The error seems to be related to the way how a path is resolved on your platform.

```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:
'/System/Volumes/Data/home/ktietz/src/ci/alabaster_1611921544520/work'
```

Could you try to run it without tflocal but using a real AWS account?

Also, please run code in `examples` to make sure that it works well for you. It is much easier to confirm those before trying to understand custom platforms.

**Comment by paultipper** [comment]
@antonbabenko Anton,

I tried using the standard terraform command to apply the infrastructure to a real AWS account, and got exactly the same error. 

Given that the first element in the `source_path` array appears to complete successfully, I'm guessing that the error has something to do with the `pip_requirements` phase (i.e. the second element):

```json
{
      path = "${path.root}/../api",
      pip_requirements = true
    }
```
Is there any way I can ascertain a) whether terraform-aws-lambda is actually able to find and read the requirements.txt file, and b) what file or directory is triggering the `No such file or directory` error message?

**Comment by paultipper** [comment]
@antonbabenko OK, so I think I know what's going on here. The real root of my problem is that terraform-aws-lambda doesn't appear Python projects that have their dependencies specified in a `setup.py` file, rather than in a `requirements.txt` file. I tried to work around this by generating a requirements.txt file using the `pip freeze` command; this worked, but unfortunately the resulting requirements file contained lots of dependency specifiers similar to the following:

```
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
```

The '@ file:///' specifier appears to have led to the `No such file or directory` errors I reported above.

It'd be really nice if terraform-aws-lambda supported the specification of a directory (e.g. '.') as the value of the `pip_requirements` parameter, and even nicer if it would allow the specification of extras, too (as specified in [the PEP 508 spec](https://peps.python.org/pep-0508/#extras)), e.g. `.[dev]`. I've cloned the repo, so I might try to get this working locally myself - if I succeed, I'll let you know, otherwise I'll raise a feature request.

**Comment by tcco** [comment]
This isn't a fix for the issue identified but a workaround thatll enable lambda python distributions managed by setuptools

```
resource "null_resource" "pip_distribution" {
  triggers = {
    always_run = "${timestamp()}"
  }
  provisioner "local-exec" {
    command = "rm -rf ./dist && pip install \".\" -t ./dist"
  }
}
```

Then set `source_path=dist` in the lambda module
