### ISSUE TITLE
Lambda Event Source Mapping remain disabled after re-creating lambdas

### ISSUE THREAD

**Issue by hussainbani** [terraform-aws-modules/terraform-aws-lambda#317]
After recreating lambdas. event source mapping remains disabled until terraform is re-applied. The fix should be simple as enabling it by default.

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/e7bfddf314bf915bfb4b2d58b6740f1d6c376be3/main.tf#L243

This should be **true** by default as the creation is already controlled via for_each.

**Comment by antonbabenko** [comment]
I think you are right, please submit a PR.

**Comment by antonbabenko** [comment]
Fixed in #321
