### ISSUE TITLE
Better Local Package Testing

### ISSUE THREAD

**Issue by schneider10** [terraform-aws-modules/terraform-aws-lambda#318]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality
Yes, v1 or earlier
## Is your request related to a problem? Please describe.

I would love to be able to generate a build package locally using the method from package.py so I can peer into its contents during debugging. The 'pattern' regexp used is very difficult to debug and I don't find the debug logs to be as useful as having direct access to the actual zip directory.
## Describe the solution you'd like.

Allow devs to run a command that accesses the same functionality behind package.py so we can generate zip files locally for debugging without having to run any terraform commands.

## Describe alternatives you've considered.

rerunning terraform apply over and over again to debug.

**Comment by lorengordon** [comment]
I'd be interested in this also. It would be useful to build the package locally without having to run the apply.

**Comment by antonbabenko** [comment]
`terraform apply` should mean "create something".

If you don't want to deploy a Lambda Function, you can always use `terraform apply -target=module.lambda_function.null_resource.archive` (or something like that).

**Comment by lorengordon** [comment]
That's not a bad idea. I rarely use `-target` and forget it is an option. Thanks Anton!
