### ISSUE TITLE
When new env variable is added, AWS provider produces inconsistent plan

### ISSUE THREAD

**Issue by tarys** [terraform-aws-modules/terraform-aws-lambda#328]
## Versions

- Module version: 3.3.1
- Terraform version: v1.2.4 on linux_amd64
- Provider version(s):
-- provider registry.terraform.io/hashicorp/aws v4.22.0
-- provider registry.terraform.io/hashicorp/external v2.2.2
-- provider registry.terraform.io/hashicorp/local v2.2.3
-- provider registry.terraform.io/hashicorp/null v3.1.1

## Reproduction Code

Steps to reproduce the behaviour:
1. Do initial deployment of Lambda with env variables section:
```terraform
module "my_lambda" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "3.3.1"

  function_name = "my-lambda"

  timeout     = 900
  memory_size = 128

  runtime = "python3.9"

  source_path = "lambda"
  handler     = "handler.run"

  environment_variables = {
    MY_VAR_1 = "value1"
    MY_VAR_2 = "value2"
  }

  cloudwatch_logs_retention_in_days = 7
}
```
2. Add new env variable:
```terraform
...
environment_variables = {
  ...
  MY_VAR_3 = "value3"
}
...
``` 
3. Deploy Lambda again

Are you using workspaces?
No

Have you cleared the local cache (see Notice section above)?
Yes

## Expected behaviour

`terraform apply` completes successfully.

## Actual behaviour

`terraform apply` fails with error.

### Terminal Output Screenshot(s)

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.my_lambda.aws_lambda_function.this[0] to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .source_code_hash: was
│ cty.StringVal("JV7yUMixOJCG7XuCa3mEnHoiXY1KdqjKNr5uUZw4WPU="), but now
│ cty.StringVal("udLJogje0z3p3KZS2JZx6DuSeneGcACuNVzdnW5I3/A=").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by x539** [comment]
this is BTW not the "provider's own issue tracker"

For the aws-provider see: https://github.com/hashicorp/terraform-provider-aws
