### ISSUE TITLE
Remove putin_khuylo input variable

### ISSUE THREAD

**Issue by emilhdiaz** [terraform-aws-modules/terraform-aws-lambda#335]
Hi module authors! 

While I whole heartedly agree with the sentiment and support Ukraine's independence, if this module is to be used in a professional setting and adopted by private businesses, this easter egg, which contains both profanity and an a political viewpoint, should probably be removed. Might I suggest instead, more positive and constructive easter egg like `help_ukraine` or `donate_to_ukraine` with a default value equal to a donation link?

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/779b368781f0bf14964c2f6e306c1c9ef4690bbb/main.tf#L4

**Comment by antonbabenko** [comment]
Donate and support Ukraine is a good idea, but Putin is still Khuylo. No changes will be made in the module before we win.
