### ISSUE TITLE
Logging permission for Lambda@Edge restricted to us-east-1

### ISSUE THREAD

**Issue by ofhouse** [terraform-aws-modules/terraform-aws-lambda#34]
Hi, while playing around with Lambda@Edge I noticed that the deployed Lambdas were not logging anything to CloudWatch.

So I looked into the created cloudwatch policy and noticed that the log creation is currently restricted to the region where the lambda is deployed to:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": [
        "logs:PutLogEvents",
        "logs:CreateLogStream"
      ],
      "Resource": [
        "arn:aws:logs:us-east-1:123456789001:log-group:/aws/lambda/us-east-1.lambda-edge-test:*:*:*",
        "arn:aws:logs:us-east-1:123456789001:log-group:/aws/lambda/us-east-1.lambda-edge-test:*:*"
      ]
    }
  ]
}
```

While this is reasonable for normal Lambdas, Lambda@Edge uses the CloudWatch region which is [closest](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-cloudwatch-metrics-logging.html#lambda-cloudwatch-logs) to it's execution runtime so I think it would be better to drop the region from the resource when using Lambda@Edge:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": [
        "logs:PutLogEvents",
        "logs:CreateLogStream"
      ],
      "Resource": [
        "arn:aws:logs:*:123456789001:log-group:/aws/lambda/us-east-1.lambda-edge-test:*:*:*",
        "arn:aws:logs:*:123456789001:log-group:/aws/lambda/us-east-1.lambda-edge-test:*:*"
      ]
    }
  ]
}
```

Don't know if there is a better solution for changing the region in an ARN, I added this code in `iam.tf` to change the arn scope:

```diff
+ data "aws_arn" "log_group_arn" {
+  arn = local.log_group_arn
+ }

+ locals {
+  log_group_arn_region = var.lambda_at_edge ? "arn:${data.aws_arn.log_group_arn.partition}:${data.aws_arn.log_group_arn.service}:*:${data.aws_arn.log_group_arn.account}:${data.aws_arn.log_group_arn.resource}" : local.log_group_arn
+ }

data "aws_iam_policy_document" "logs" {
  count = local.create_role && var.attach_cloudwatch_logs_policy ? 1 : 0

  statement {
    effect = "Allow"

    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents",
    ]
-   resources = flatten([for _, v in ["%v:*", "%v:*:*"] : format(v, local.log_group_arn)])
+   resources = flatten([for _, v in ["%v:*", "%v:*:*"] : format(v, local.log_group_arn_region)])
  }
}
```

**Comment by antonbabenko** [comment]
Lambda@Edge is special kind of Lambda function, which is required to be deployed in us-east-1 along with the log groups.

Do you say that it doesn't log there?

**Comment by ofhouse** [comment]
Yeah it is deployed in `us-east-1` but it actually logs to the region where it's executed.

Let's say the viewer-request comes from Frankfurt, Germany:
The lambda is then executed in `eu-central-1` (Frankfurt) and the logs for that execution are also written to the CloudWatch in `eu-central-1`.

It's a bit complicated because that means to give terraform control over all log groups it have to create log groups in all regions. (https://advancedweb.hu/how-to-manage-lambda-log-groups-with-terraform/#lambdaedge)

**Comment by antonbabenko** [comment]
Now I see what you mean. I will try to take a look at this issue later this week. Maybe you can open a pull-request?

**Comment by ofhouse** [comment]
Sure, no problem. Opened #35
