### ISSUE TITLE
terraform-aws-modules/lambda/aws V 3.3.1 Isn't working as of Aug 10

### ISSUE THREAD

**Issue by melissarh57** [terraform-aws-modules/terraform-aws-lambda#340]
## Description

Is anyone else running into an issue where terraform-aws-modules/lambda/aws doesn't work as expected as of around Noon  CST 8/10/22? 

I'm getting errors like 

`Error: Unsupported argument

  on lambda.tf line 21, in module "lambda_function":
  21:   function_name      = "function-name"

An argument named "function_name" is not expected here.

Error: Unsupported argument

  on lambda.tf line 22, in module "lambda_function":
  22:   description        = "description here"

An argument named "description" is not expected here.

Error: Unsupported argument

  on lambda.tf line 23, in module "lambda_function":
  23:   handler            = "handlervalue"`

## Versions

- Module version [3.3.1]:

=- Provider version(s):
hashicorp/aws v4.25.0
terraform version: latest v1.2.7

## Reproduction Code [Required]

Run terraform plan changing anything in the lambda module: terraform-aws-modules/lambda/aws using v 3.3.1

## Expected behavior

It should work fine

## Actual behavior

Getting tons of errors of passing in attributes when it says the module shouldn't retrieve that attribute: like "function_name"

**Comment by jonohill** [comment]
I'm getting the same issue today, but it seems be a problem with the new Terraform release https://github.com/hashicorp/terraform/issues/31615
Downgrading to v1.2.6 of Terraform resolves the issue.

**Comment by antonbabenko** [comment]
There was an issue on the Terraform Registry side. It has been resolved.
