### ISSUE TITLE
Variable provisioned_concurrent_executions should have default set to null

### ISSUE THREAD

**Issue by hammadzz** [terraform-aws-modules/terraform-aws-lambda#38]
I suggest that `null` be used to disable setting the provisioned concurrency config. Otherwise the description of the variable that it must be greater greater than or equal to 1 contradicts itself by having the default as -1.

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/5ab6ccbd5566cb2e3cdeb0d2cae5ce4950be711c/variables.tf#L226-L230

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/5ab6ccbd5566cb2e3cdeb0d2cae5ce4950be711c/main.tf#L119-L126

**Comment by antonbabenko** [comment]
-1 means `provisioned concurrency is not managed, not set`;
0 - disable;
1+ - means enable provisioned concurrency.

`null` is not a valid value, because `provisioned_concurrent_executions` is the required argument.

The description is almost always taken from AWS provider resources.

**Comment by hammadzz** [comment]
The description is taken from AWS provider resources but it becomes inaccurate in this case because -1 is never a valid value in the [aws_lambda_provisioned_concurrency_config](https://www.terraform.io/docs/providers/aws/r/lambda_provisioned_concurrency_config.html) resource. 

I do understand that in this module it is a valid value. But do you see how -1 as the default for the module `provisioned_concurrent_executions` variable leads to confusion as it conflicts the description of that variables which states "Must be greater than or equal to 1"?

So passing null seems like a more clear "not managed and not set".
