### ISSUE TITLE
Building Dependencies Works Even if a Command Fails

### ISSUE THREAD

**Issue by p0fi** [terraform-aws-modules/terraform-aws-lambda#388]
## Description
When using the build dependencies functionality of this module via the `commands` array the success of any given command is not considered when running the next commands form the array.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: `4.0.0`

- Terraform version: 
```
Terraform v1.3.5
on darwin_arm64
```
- Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v4.45.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.1
```

## Reproduction Code [Required]

If a commands array might look like this:

```js
commands = [
  "yarn install",
  "yarn build",
  ":zip dist/index.js ."
]
```

Every command is still run, no matter how the previous command exited. It does not make sense to run a `build` if an `install` failed and furthermore a `zip` would result in something completely different from what is expected.

1. Modify the install command to make it fail. 
2. Run `terraform apply`

## Expected behavior
Apply would fail with an error message.

## Actual behavior
Apply works fine but lambda code is not working since it was not build correctly. 

### Terminal Output Screenshot(s)
–

## Additional context
Noticed the problem when yarn install commands would fail in CI but the run was "successful" but lambdas didn't work.

**Comment by p0fi** [comment]
This is still an issue

**Comment by p0fi** [comment]
This is still a problem

**Comment by p0fi** [comment]
This is still an issue 😢

**Comment by vecchp** [comment]
I believe this is still an issue
