### ISSUE TITLE
attach_policies not working without number_of_policies

### ISSUE THREAD

**Issue by Ewande** [terraform-aws-modules/terraform-aws-lambda#39]
It seems like `attach_policies`+`policies` don't work by themselves from 1.3.0 ([this](https://github.com/terraform-aws-modules/terraform-aws-lambda/commit/166f71a0ad7373918164900e6a53fe26a9100d3c) commit) and you need to manually set `number_of_policies` to make it work, unless I'm missing something:
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/6971d6cc91fcde6e359928b0e2a2a206bf4a85e4/iam.tf#L239

It's not mentioned in the README and in [the example](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/5ab6ccbd5566cb2e3cdeb0d2cae5ce4950be711c/examples/complete/main.tf#L82).

Why can't it be automatically derived from the number of records in `policies` and what was the motivation behind the change?

**Comment by antonbabenko** [comment]
Good catch, I have just updated an example (4fd3c09).

The motivation for using `number_of_policies` is to have a workaround for "value of 'count' cannot be computed".

See [this note about "value of 'count' cannot be computed"](https://github.com/terraform-aws-modules/terraform-aws-security-group/#note-about-value-of-count-cannot-be-computed) from another module.
