### ISSUE TITLE
Add ability to set consumer group names for Amazon Managed and Self Managed Kafka cluster

### ISSUE THREAD

**Issue by wilkejo** [terraform-aws-modules/terraform-aws-lambda#397]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: v4.29.0
  
`resource/aws_lambda_event_source_mapping: Add amazon_managed_kafka_event_source_config and self_managed_kafka_event_source_config configuration blocks`

## Is your request related to a problem? Please describe.
The configuration blocks `self_managed_kafka_event_source_config` or `amazon_managed_kafka_event_source_config` are not considered by the module. Therefore it isn't possible to define the consumer group name. This is necessary as in our Kafka setup, the  ACLs only allow specific consumer group names for specific user

## Describe the solution you'd like.
add the both new blocks as additional dynamic (?) blocks on the same level as  `dynamic "self_managed_event_source"`

## Describe alternatives you've considered.
Couldn't find and alternative to setup the consumer group name

**Comment by wilkejo** [comment]
not stale. MR is still open

**Comment by Nunalves** [comment]
What's blocking this issue from being merged? Really need this feature also.
