### ISSUE TITLE
aws_iam_policy_attachment used for additional policies

### ISSUE THREAD

**Issue by Ewande** [terraform-aws-modules/terraform-aws-lambda#40]
`aws_iam_policy_attachment` creates exclusive attachments, I think it makes more sense to use `aws_iam_role_policy_attachment` in those cases:
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/5ab6ccbd5566cb2e3cdeb0d2cae5ce4950be711c/iam.tf#L226
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/5ab6ccbd5566cb2e3cdeb0d2cae5ce4950be711c/iam.tf#L238

**Comment by codeninja55** [comment]
This should be the case for all attachments as it can override or removing existing policies from other roles.

**Comment by Ewande** [comment]
As far as I can see, these two are the only ones that allow using existing policies. Other attachments either create new policies or use inline policies.

**Comment by jasonhuling** [comment]
I just ran into this issue as well... does anyone know if there are any plans to correct this?

**Comment by antonbabenko** [comment]
I agree, it makes sense, fixed in #45, [v1.20.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.20.0) has been just released.
