### ISSUE TITLE
creation of IAM role missing policy for VPC

### ISSUE THREAD

**Issue by hammadzz** [terraform-aws-modules/terraform-aws-lambda#41]
This module supports Lambda in VPC but does not add necessary network interface permissions.

You would need this or attach the managed policy
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:DescribeNetworkInterfaces",
        "ec2:CreateNetworkInterface",
        "ec2:DeleteNetworkInterface",
        "ec2:DescribeInstances",
        "ec2:AttachNetworkInterface"
      ],
      "Resource": "*"
    }
  ]
}
```

**Comment by hammadzz** [comment]
Should have read the docs, there is an explicit vpc flag `attach_network_policy = true` required

Could this not be achieved using a check like so `is_in_vpc = var.vpc_subnet_ids !== null`?

**Comment by Ewande** [comment]
> Could this not be achieved using a check like so `is_in_vpc = var.vpc_subnet_ids !== null`?
If you use an existing role (i.e. `lambda_role` parameter), you might not want to automatically attach vpc permissions even if you specify vpc subnets, so this check would need to be more complex.

**Comment by antonbabenko** [comment]
I agree with @Ewande .

Also, if you need to attach any additional policies you can do it in several ways.

Closing this issue.
