### ISSUE TITLE
filter_criteria not works for source kinesis stream: aws_lambda_event_source_mapping

### ISSUE THREAD

**Issue by adamyanlina** [terraform-aws-modules/terraform-aws-lambda#413]
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/f4861b751c5f89daecc2788069d67baaf4653b75/examples/event-source-mapping/main.tf#L43

Here is my filter_criteria:
  filter_criteria {
    filter {
      pattern = jsonencode({
        data: {
          typeId: [210],
          locally: [{"exists": true}]
        }
      })
    }
  }

**Comment by antonbabenko** [comment]
Here is an example of event sourcing with Kinesis Streams:

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/eface07424982cea49edd4f6665e05741490b370/examples/event-source-mapping/main.tf#L50-L61
