### ISSUE TITLE
Zip quiet mode

### ISSUE THREAD

**Issue by anthonyangel** [terraform-aws-modules/terraform-aws-lambda#421]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
Currently when running this lambda I get 1000's of log lines as packages as added to the zipfile, these provide no value to me, and clutter the logs

## Describe the solution you'd like.
The option of passing in `zip_quiet` as an argument, which would result in the (python equivalent) of `zip -qq` when the Terraform is applying.

**Comment by antonbabenko** [comment]
Good point. PR is welcome.

**Comment by k5njm** [comment]
I just performed a test, adding `TF_LAMBDA_PACKAGE_LOG_LEVEL=WARNING` or any other less verbose log level will suppress the (potentially hundreds of)  `zip: adding:` lines, but will not suppress the `docker` or `pip` output.
