### ISSUE TITLE
Managed cloudwatch log group has retention_in_days parameter

### ISSUE THREAD

**Issue by eugene-komar-bmll** [terraform-aws-modules/terraform-aws-lambda#439]
It would nice to have an optional `retention_in_days` parameters to log group created with this module.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#retention_in_days

**Comment by magreenbaum** [comment]
There is this [cloudwatch_logs_retention_in_days](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/main.tf#L188) variable in the module you can set.
