### ISSUE TITLE
Add support for build, package & deploy of Golang + arm64 + provided.al2

### ISSUE THREAD

**Issue by vainkop** [terraform-aws-modules/terraform-aws-lambda#455]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

It doesn't look possible to use the current implementation of the module & `package.py` to build, package & deploy a `Golang` lambda for `arm64` for `provided.al2` runtime (which is the only run time at the moment working with arm64 Golang)

## Describe the solution you'd like.
To be able to configure build, package & deploy for Golang + arm64 + provided.al2 runtime out of the box.

It is probably a good idea to make it possible to fully redefine the commands used for the build inline + be able to use external Makefile regardless of the runtime & architecture.

A simple example of a Golang + arm64 build + package:
```
env GOOS=linux GOARCH=arm64 go build -o bootstrap src/main.go
zip -j deploy.zip bootstrap
```

https://docs.aws.amazon.com/lambda/latest/dg/golang-package.html

https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-to-arm-based-aws-graviton2-processors/

https://github.com/mthenw/serverless-go-plugin/blob/master/README.md#how-to-run-golang-lambda-on-arm

**Comment by vi2co** [comment]
+1 to keep this issue open

**Comment by villekr** [comment]
ARM64 AL2 would be also interesting. How would one use this module for deploying Go Lambda for X86_64 architecture? Simple example would be nice. I've used this module so far with Python and Node.js with layers so will start to look also using this with Go.

**Comment by vi2co** [comment]
@villekr 
I would like to use it for [Loki Promtail Lambda](https://github.com/grafana/loki/tree/main/tools/lambda-promtail/lambda-promtail) (X86_64 or ARM64).
So far I just put compiled Lambda archive into my Terraform repo. But I would like to automate this process with Terraform e.g. download the source code from Github, build it and deploy Lambda.

**Comment by vainkop** [comment]
It looks pretty clear that to add Golang builds support one needs to either work on [package.py](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v4.18.0/package.py#L776) or add a condition into [package.tf](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v4.18.0/package.tf#L8) which will trigger a different script for Golang + provided.al2 runtime.
Too bad I don't have time to implement it at the moment, hopefully I will find it soon.
