### ISSUE TITLE
Add support for python3.10 runtime 

### ISSUE THREAD

**Issue by behnamIW** [terraform-aws-modules/terraform-aws-lambda#460]
## Is your request related to a new offering from AWS?
  - Yes ✅: AWS has recently added support for Python 3.10 for lambda functions.

## Is your request related to a problem? Please describe.
When I set
```
runtime       = "python3.10"
```
I get this error:
```
Error: expected runtime to be one of [nodejs nodejs4.3 nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x nodejs14.x nodejs16.x java8 java8.al2 java11 python2.7 python3.6 python3.7 python3.8 python3.9 dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 dotnet6 nodejs4.3-edge go1.x ruby2.5 ruby2.7 provided provided.al2 nodejs18.x], got python3.10
```

https://serverlessland.com/blog/python-310-runtime-now-available-in-aws-lambda--aws-compute-blog

**Comment by antonbabenko** [comment]
Make sure that you are using Terraform AWS provider version 4.64.0 or newer. Run `terraform init -upgrade` to update it.

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4640-april-20-2023

There is nothing we should do in this module to get support for the new runtimes.
