### ISSUE TITLE
Add Python runtime 3.10

### ISSUE THREAD

**Issue by JulianAWS** [terraform-aws-modules/terraform-aws-lambda#465]
## Is your request related to a new offering from AWS?
Yes ✅: please list the AWS provider version which introduced this functionality
  - https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/

## Is your request related to a problem? Please describe.
I'm frustrated when I can not use Python3.10

## Describe the solution you'd like.
Add a Lambda function and layer with runtime Python 3.10

## Describe alternatives you've considered.
Using Python3.9

**Comment by antonbabenko** [comment]
Please read this for the explanation - https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/460#issuecomment-1547619499
