### ISSUE TITLE
Ignoring some local directories on build

### ISSUE THREAD

**Issue by benjamin9fin** [terraform-aws-modules/terraform-aws-lambda#472]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.

Yes. It would be useful if the module offered a way to ignore some local directories (`node_modules` for example) when building a lambda.

## Describe the solution you'd like.

The lambda module could have an `ignore` option and `package.py` could be instructed to ignore certain directories/files which aren't needed for the build (in a similar way to `.dockerignore` for example).

## Describe alternatives you've considered.

Creating a separate build directory prior to running any terraform commands and copying only required files into it.

**Comment by adrianisk** [comment]
You can use the [patterns](https://registry.terraform.io/modules/terraform-aws-modules/lambda/aws/latest#patterns) argument when specifying source paths to filter out files & directories

**Comment by antonbabenko** [comment]
@adrianisk Has just answered the question. Thank you!

I am closing this issue.
