### ISSUE TITLE
Add suppurt f

### ISSUE THREAD

**Issue by ulielitay** [terraform-aws-modules/terraform-aws-lambda#480]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality: >= 3.75.2
  -

## Is your request related to a problem? Please describe.
I'm using ecr images, each time i want to run the TF the ecr image + environment variables are changed to the TF one and not the already exist by the pipeline

## Describe the solution you'd like.
add life cycle to the resources so we can "one time deploy" (or add the option to add to the module from our side what to ignore
https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle

i have it in my own personal module i've created

  environment {
    variables = var.environment_variables
  }

  lifecycle {
    ignore_changes = [
      environment,
      filename,
      source_code_hash,
      source_code_size,
      last_modified,
      image_uri
    ]
  }

**Comment by antonbabenko** [comment]
Terraform doesn't support the usage of variables inside of `lifecycle` `ignore_changes`, so we can't make it part of the module.
