### ISSUE TITLE
Expose create / update timeout config

### ISSUE THREAD

**Issue by omerlh** [terraform-aws-modules/terraform-aws-lambda#484]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform]
  - Yes ✅: please list the AWS provider version which introduced this functionality
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#timeouts

I can see it in the latest version

## Is your request related to a problem? Please describe.

Yes, we are deploying lambda functions using containers and deployments consistently fails on the first deployment with:

```
Error: publishing Lambda Function (create-integration-line-lambda_main) version: waiting for completion: exceeded max wait time for FunctionUpdated waiter
```

Retrying the build solves the problem.

## Describe the solution you'd like.
Looking at `aws_lambda_function` I can see it exposes timeout configs for update / create which I want to increase.

## Describe alternatives you've considered.
I have no idea...

**Comment by antonbabenko** [comment]
This issue has been resolved in version 5.3.0 :tada:
