### ISSUE TITLE
Allow dynamic tagging for existing lambda resources

### ISSUE THREAD

**Issue by moranimu** [terraform-aws-modules/terraform-aws-lambda#496]
I was trying to add tags to an existing lambda function managed by Terraform.
During my trials, I saw that it is even impossible to modify a tag.

Having the ability to update/add tags would allow us to better monitor lambdas execution over time and react according to the values of the tags 

Currently we are using version 4.2.1 of this module

**Comment by moranimu** [comment]
Any update on this issue?

**Comment by moranimu** [comment]
Any update on this issue?

**Comment by moranimu** [comment]
Any update on this issue?

**Comment by moranimu** [comment]
Any update on this issue?

**Comment by antonbabenko** [comment]
You should be able to specify `function_tags` and/or `tags` as shown in the example - https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/complete/main.tf#L174-L180

This feature has been supported since day one.

**Comment by moranimu** [comment]
@antonbabenko we are using `tags`, I was looking for a way to modify the existing tags.

**Comment by antonbabenko** [comment]
If the function was created using this module, you should be able to adjust `tags`. If not, you can import it or recreate using this module.
