### ISSUE TITLE
docs + commands: update complete & build docs with examples for custom build commands & languages other than Python & Node

### ISSUE THREAD

**Issue by vainkop** [terraform-aws-modules/terraform-aws-lambda#497]
I've previously created an [issue](https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/455) to implement `go build` functionality in the lambda module & since then I've created a custom solution using separate resources but it seems that it was possible to use `source_path` + `commands` for that which is reflected only in the root [README.md](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/v4.18.0/README.md?plain=1#L428-L432) but not in a complete or build examples so it's not easy to find this info.

**Comment by antonbabenko** [comment]
I agree, it would be great to have working examples for various programming languages (runtimes) supported by Lambda shown in `examples/runtimes`. Leave `examples/build-package` focused on various types of building packages.

If you have a possibility to make a PR at least for Go, it would be a great start.
