### ISSUE TITLE
Add variable to manage the CreateLogGroup permission

### ISSUE THREAD

**Issue by jake-naughton** [terraform-aws-modules/terraform-aws-lambda#503]
## Is your request related to a new offering from AWS?
- Already exists.

## Is your request related to a problem? Please describe.
I have to manage IAM roles outside of this module because it enforces `logs:CreateLogGroup` permission when the module provisions the CloudWatch log group. However, there are many cases where you don't need or want this permission attached to your lambda and it is a nuisance when you are dealing with ephemeral environments. The problem is described in this issue:
https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/342

## Describe the solution you'd like.
To add a variable that allows for the `logs:CreateLogGroup` to be turned off even when the module is responsible for provisioning the CloudWatch logs. By default it would be on so no change in behaviour.

```
variable "attach_create_log_group_permission" {
  description = "..."
  type             = bool
  default        = true
}

```

```
data "aws_iam_policy_document" "logs" {
  count = local.create_role && var.attach_cloudwatch_logs_policy ? 1 : 0

  statement {
    effect = "Allow"

    actions = compact([
      !var.use_existing_cloudwatch_log_group && var.attach_create_log_group_permission ? "logs:CreateLogGroup" : "",
      "logs:CreateLogStream",
      "logs:PutLogEvents"
    ])

    resources = flatten([for _, v in ["%v:*", "%v:*:*"] : format(v, local.log_group_arn)])
  }
}
```

## Describe alternatives you've considered.
Creating my own IAM role outside of the module and passing it in. Could also create the CloudWatch log group outside of the module.

## Additional context
Happy to put up a PR for this improvement if it is acceptable.

**Comment by KamilBlaz** [comment]
Hello, can I take care of it?

**Comment by jake-naughton** [comment]
Any thoughts on this?

**Comment by antonbabenko** [comment]
Hi @jake-naughton !

Please make a PR with the proposed change.

**Comment by jake-naughton** [comment]
Hi @antonbabenko, I have raised the PR here: https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/514
