### ISSUE TITLE
lambda.null_resource.archive[0] must be replaced

### ISSUE THREAD

**Issue by 123BLiN** [terraform-aws-modules/terraform-aws-lambda#51]
Hi, thanks for your awesome work!

We are using this module from another terraform-aws-module https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/v3.4.0/main.tf
And every new run triggers new resource:
```
  # module.cloudwatch_monitoring.module.notify_slack.module.lambda.null_resource.archive[0] must be replaced
-/+ resource "null_resource" "archive" {
      ~ id       = "5319273782967310555" -> (known after apply)
      ~ triggers = { # forces replacement
            "filename"  = "builds/5263a8b288d3aa735f5e3f690df38b5c344b6148f53581dd46fd72f43a77a3d3.zip"
          ~ "timestamp" = "1597778885990253000" -> "1598388524692038000"
        }
    }
```
I have not dig deep yet, however I wonder maybe this line is not required?
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/package.tf#L54

P.S. It seems that it is only reproducible if more than one person is working on the same terraform code.

**Comment by Nickmman** [comment]
Confirmed that this happens every time when run via Terraform Enterprise (remote backend).

**Comment by antonbabenko** [comment]
Hi guys,

Please make sure that you set the environment variable `TF_RECREATE_MISSING_LAMBDA_PACKAGE=false` and run `terraform apply`.

Also, see detailed explanation in the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-lambda#faq).

Let me know if this solves the problems and I will update the documentation of the `notify-slack` module.

**Comment by Nickmman** [comment]
I completely missed that entry in the FAQ, my bad. That solved the issue for me, thanks.

**Comment by Nickmman** [comment]
@antonbabenko Circling back on the environment variable you mentioned.. For TFE, does that mean that it needs to be set/unset each time that there's a change that we want pushed out? Set to true on plan but false on apply? Or what is the best approach there?

**Comment by ahlinc** [comment]
No, it doesn't need to be unset, just keep the mentioned env var set to false permanently. TFE environment is special in a sence that everything in it starts from scratch so a lambda package will be created in any case and where any changes related to a content of lambda package will also force related lambda function redeployment.

**Comment by 123BLiN** [comment]
It seems now I got it - it will be only created once per terraform user of the shared repo.
Solved for me.

**Comment by 123BLiN** [comment]
Just tested again and it is not recreating, closing.

**Comment by davids13** [comment]
Hi,
There is a similar command of recreate_missing_package for Azure?

**Comment by savitafulmali** [comment]
I tried multiple times setting environment variable using command export TF_RECREATE_MISSING_LAMBDA_PACKAGE=false before running terraform ini, followed by terraform plan command locally. Added recreate_missing_package = false in module but its not at all working.
I am using terraform version Terraform v1.3.1
+ provider registry.terraform.io/hashicorp/aws v4.17.1
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.0
 aws = {
      source  = "hashicorp/aws"
      version = "~> 4.17.1"
    }
source  = "terraform-aws-modules/lambda/aws"
  version = "4.6.0"
