### ISSUE TITLE
Limit number of available Lambda versions 

### ISSUE THREAD

**Issue by extsoft** [terraform-aws-modules/terraform-aws-lambda#519]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

I'm using Lambda function versioning with Aliases. Every code change creates a new function version. Over time, there is a list of the old versions that are no longer relevant. I would like to get them removed automatically due to
1. the old versions of the functions could be dangerous to deploy; someone could deploy them manually
2. the function storage (code and layers) is limited to 75GB ([AWS Lambda quotas](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)); I would like to optimize its usage

## Describe the solution you'd like.

An input called `versions_to_keep` (defaults to 50). For instance, `versions_to_keep = 5` means that the 5 resent versions of the function must remain; the rest must be removed.

## Additional context

Serverless framework has [a plugin for this task](https://www.npmjs.com/package/serverless-prune-plugin).

**Comment by antonbabenko** [comment]
There is no native way to control such a number using Terraform AWS provider resources (AFAIK) - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function

Such a solution should be a part of a dedicated module for `solutions` - https://github.com/terraform-aws-modules/terraform-aws-solutions

Pull requests are welcome.
