### ISSUE TITLE
Build plan changes don't re triggering a zip package rebuild

### ISSUE THREAD

**Issue by ahlinc** [terraform-aws-modules/terraform-aws-lambda#53]
Related to #52, what was bad attempt to fix the issue and didn't take into account situation with different paths on different environments.

### Issue
Changes into `source_path.patterns` don't make any effect but it should and the package should be rebuilt. It seems that there is the same situation with other fields in the `source_path` object.

### Solution
Take only environment independent part of the `source_path` into account for a content hash computation.

### Workaround

Use `hash_extra` to specify a string value dynamically.

**Comment by paul-pop** [comment]
Thanks for the initial work and raising this @ahlinc, are there any plans to work on this?
