### ISSUE TITLE
Not being able to use nodejs20.x as runtime

### ISSUE THREAD

**Issue by rebonat0** [terraform-aws-modules/terraform-aws-lambda#533]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
I'm not being able to use nodejs20.x runtime on terraform-aws-modules/lambda/aws, it's not available yet?

**Comment by antonbabenko** [comment]
Did you try to specify the correct `runtime` value?

https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/dcb087d610a294d9c5a29930d8a11a7ab8d4d07e/examples/complete/main.tf#L25

**Comment by rebonat0** [comment]
Hi @antonbabenko , thank's for asking!

Yeah, I tried to use runtime = "nodejs20.x"
Here's a screenshot with the error that I got:
![image](https://github.com/terraform-aws-modules/terraform-aws-lambda/assets/98909278/e8810a17-8bfc-414e-a08d-858bda7eb3b8)
