### ISSUE TITLE
Re-format code with Ruff formatter

### ISSUE THREAD

**Issue by Fran-Rg** [terraform-aws-modules/terraform-aws-lambda#535]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

## Is your request related to a problem? Please describe.
Hard to code

## Describe the solution you'd like.
The python files should all be reformated using ruff format or black: https://docs.astral.sh/ruff/formatter/

## Describe alternatives you've considered.
Not very aware of EditorCode but ruff/black works very well

## Additional context
It would help contributions

**Comment by antonbabenko** [comment]
Sounds good to me and `ruff` is nice. PR containing only ruff changes is welcome.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 7.0.0 :tada:
