### ISSUE TITLE
Add documentation covering setup for DIND (docker in docker) packaging

### ISSUE THREAD

**Issue by david-heward-unmind** [terraform-aws-modules/terraform-aws-lambda#544]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
When running the terraform module in a DIND (docker in docker) setup there are additional setup requirements. It would be good to document them.

## Describe the solution you'd like.
I would like docs to be expanded to cover a working solution for DIND since most folk will be simply mounting `/var/run/docker.sock` into the container, the commands to mount source code simply will not work as the expectation will be that the source code locations exist on the host and not container. It may also be somewhat responsible for other reported issues with missing files.

I am about to fix this for a setup. Will add some additional context and maybe even a fix as soon as I have it.

## Describe alternatives you've considered.
N/a

## Additional context
n/a

**Comment by CMorton737** [comment]
@david-heward-unmind Were you able to make any progress here? I've run into this issue myself and any guidance would be appreciated

**Comment by david-heward-unmind** [comment]
> @david-heward-unmind Were you able to make any progress here? I've run into this issue myself and any guidance would be appreciated

I did fix this. I'll try to dig up how for you.
