### ISSUE TITLE
Number of Policies unnecessary input?

### ISSUE THREAD

**Issue by Zyntogz** [terraform-aws-modules/terraform-aws-lambda#55]
Hey folks,

i appreciate your repo and regularly use its modules. However, the lambda repository has a, for me, unnecessary variable "number_of_policies", which has to be injected when supplying the "policies" variable. This variable could be derived from the length of the list in "policies". I already modified the code and wanted to push it to a feature-branch to create a PR but i get a 403. Are you interested in the change? 

Change (derive corresponding changes in variables.tf and example/complete):
_________________________________________________________________________________
iam.tf:
resource "aws_iam_role_policy_attachment" "additional_many" {
  count = local.create_role && var.attach_policies ? length(var.policies) : 0

  role       = aws_iam_role.lambda[0].name
  policy_arn = var.policies[count.index]
}
_________________________________________________________________________________

**Comment by antonbabenko** [comment]
Hi @Zyntogz !

`var.number_of_policies` is used to support cases when creating policies in the same flow and referencing them in `var.policies`. This way Terraform won't be able to identify number of policies and will fail (error like: `computed values can't be used in count`).

Closing this one.
