### ISSUE TITLE
Allow nodejs build to run npm install with --omit=dev

### ISSUE THREAD

**Issue by braun1928** [terraform-aws-modules/terraform-aws-lambda#568]
## Is your request related to a problem? Please describe.
When building node lambda, it runs just a `npm install`. If the package.json file has things in `devDependencies`, the package file may get a bit bloated unnecessarily. Specific case: one lambda goes from 4MB to 28MB, and obviously, takes a little longer to install the dependencies.

## Describe the solution you'd like.
A way to signal the build process to append `--omit=dev` with node packages.

## Describe alternatives you've considered.
Using a command list in `source_path` works, BUT that makes it not possible to use `build_in_docker`, which renders another list of issues (lots of different runtimes needed, CI pipelines, etc).

**Comment by sachasmart** [comment]
What if you create a separate resource like:
```terraform
resource "null_resource" "function_binary" {
```

**Comment by braun1928** [comment]
Workaround/clean way: set docker environment variable NODE_ENVIRONMENT to production (using docker_additional_options), the desired behaviour is achieved and no need to customize commands or anything. If not building in docker (not my case) then needs to run terraform with that variable set.

**Comment by kevcube** [comment]
@braun1928 not a great workaround for builds that are not using docker, can we reopen?

**Comment by braun1928** [comment]
@kevcube actually created #598 with more context and broader situations, as I thought of the `go` builds I have using the same process.
