### ISSUE TITLE
Error: Provider produced inconsistent final plan related qualified_arn, qualified_invoke_arn and version

### ISSUE THREAD

**Issue by hapatel-jetblue** [terraform-aws-modules/terraform-aws-lambda#586]
## Description

When I trie to apply my changes for lambda function it will throw the error of Error: Provider produced inconsistent final plan related some qualified_arn, qualified_invoke_arn and version params.

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
7.3.0
- Terraform version:
1.8.5
- Provider version(s):
>=5.0.0

## Reproduction Code [Required]

module "lambda_function_agent_desktop_etl" {
  source                 = "git@github.com:jetblueairways/ccaas-terraform-modules-wrapper.git//jb-terraform-aws-lambda?ref=main"
  prefix_company         = var.prefix_company
  lob                    = var.lob
  prefix_region          = var.prefix_region
  application            = var.application
  env                    = var.env
  description            = var.description
  name                   = format("%s-lmda-%s-%s-etl-%s-%s", var.prefix_company, var.lob, var.application, var.prefix_region, var.env)
  local_existing_package = var.local_existing_package
  handler                = var.handler
  runtime                = var.runtime
  create_role            = true
  environment_variables  = var.environment_variables
  timeout                = 900
  publish                = true
  layers                 = [module.lambda_layer_etl.lambda_layer_arn]
  allowed_triggers = {
    AllowExecutionFromEventBridgeCron1 = {
      service    = "events"
      source_arn = module.eventbridge_agent_desktop_etl.eventbridge_rule_arns["1"]
    },
    AllowExecutionFromEventBridgecron2 = {
      service    = "events"
      source_arn = module.eventbridge_agent_desktop_etl.eventbridge_rule_arns["2"]
    },
    AllowExecutionFromEventBridgecron3 = {
      service    = "events"
      source_arn = module.eventbridge_agent_desktop_etl.eventbridge_rule_arns["3"]
    },
    AllowExecutionFromEventBridgefailover = {
      service    = "events"
      source_arn = module.eventbridge_agent_desktop_etl.eventbridge_rule_arns["Agent_desktop_active_region_failover"]
    }
  }
  attach_policy_jsons    = true
  policy_jsons           = [data.aws_iam_policy_document.etl_lambda_policy.json]
  number_of_policy_jsons = 1
  vpc_subnet_ids         = var.app_subnet_ids
  vpc_security_group_ids = ["${aws_security_group.lambda_function_agent_desktop_etl_sg.id}"]
  attach_network_policy  = true
}

### Terminal Output Screenshot(s)

Error: Provider produced inconsistent final plan

When expanding the plan for
module.lambda_function_agent_desktop_etl.module.lambda_function.aws_lambda_function.this[0]
to include new values learned so far during apply, provider
"registry.opentofu.org/hashicorp/aws" produced an invalid new value for
.qualified_arn: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.lambda_function_agent_desktop_etl.module.lambda_function.aws_lambda_function.this[0]
to include new values learned so far during apply, provider
"registry.opentofu.org/hashicorp/aws" produced an invalid new value for
.qualified_invoke_arn: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
module.lambda_function_agent_desktop_etl.module.lambda_function.aws_lambda_function.this[0]
to include new values learned so far during apply, provider
"registry.opentofu.org/hashicorp/aws" produced an invalid new value for
.version: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

## Additional context

![image](https://github.com/terraform-aws-modules/terraform-aws-lambda/assets/165931133/d0826f22-fea6-4024-a707-6b4bb6ed52b4)

**Comment by pdecat** [comment]
Does it work on second apply?
