### ISSUE TITLE
Ignore image_uri changes 

### ISSUE THREAD

**Issue by dgonzalezfintonic** [terraform-aws-modules/terraform-aws-lambda#591]
## Is your request related to a problem? Please describe.
Hi, I would like a feature to ignore_image_uri to deploy new versions of lambda function from CICD without doing changes in Terraform

**Comment by faissaloo** [comment]
This is a feature that has been requested many times: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues?q=is%3Aissue+ignore+image_uri+is%3Aclosed
I would also like to second this, as it's become a bit annoying
