### ISSUE TITLE
Inappropriately expecting a decorated plan.json and plan.cache in GitLab

### ISSUE THREAD

**Issue by spliskamatyshak** [terraform-aws-modules/terraform-aws-lambda#593]
## Description

When applying the code to create a Python lambda using this module in GitLab, the apply fails because the module is looking for plan.json with the random string used for the name of the zip file as a prefix on plan.json (i.e., <long_random_string>.plan.json. The plan.json is not being created as an artifact in this way. It is just plan.json. When the apply executes, something in your code looks for the decorated plan file instead of the one produced as an artifact (plan.json) for the apply stage.
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version: 7.7.0

- Provider version(s): 5.57.0

## Reproduction Code [Required]

Oddly enough, the first time after the artifact_path is modified in the code (introduced, changed, or removed), the apply stage works fine. However, subsequent deployments fail with the behavior described.

This uses GitLab's CI template for Terraform; this behavior doesn't occur at the command line.

## Expected behavior
The apply stage of the pipeline should not look for the decorated plan.json, which is never created. I'm not sure plans should EVER be manipulated by a module. 

## Actual behavior
The apply stage fails because it looks for the decorated plan.json, which isn't created as an artifact in the plan stage of the pipeline.

### Terminal Output Screenshot(s)
I will upload them when I can access them from another account.

**Comment by pdecat** [comment]
I believe you need to either specify the `artifacts_dir` input of the lambda function and add it to the plan job artifacts, or add all `*.plan.json` as job artifacts.

**Comment by pdecat** [comment]
This `builds/168bb3e027704854948afc04565ef12ac1c2eafb480af24cfc20df5c1b0723a6.plan.json` is generated by the terraform-aws-lambda module at plan time to determine the content of the `builds/168bb3e027704854948afc04565ef12ac1c2eafb480af24cfc20df5c1b0723a6.zip` archive.

**Comment by spliskamatyshak** [comment]
Why? The GitLab pipeline already creates a plan file. I've tried saving this other plan file as an artifact in the pipeline (as you alluded to in your first comment), but the pipeline never uploads it because it isn't there. It's like it's never been created.

**Comment by pdecat** [comment]
It does not serve the same purpose as the terraform plan file, it is really specific to the packaging of the lambda that is done by this module.

The packaging process is described here: https://github.com/terraform-aws-modules/terraform-aws-lambda?tab=readme-ov-file#-how-does-building-and-packaging-work

You can try to enable debug logging to understand what is going on, see https://github.com/terraform-aws-modules/terraform-aws-lambda?tab=readme-ov-file#-debug

**Comment by spliskamatyshak** [comment]
I figured it out. The fact that the decorated plan.json isn't THE plan.json is very confusing. Couldn't it be named something else?
GitLab requires artifacts from the artifact_path and the module.path to be uploaded since setting one specifically trumps the automatic artifact the pipeline does for Terraform.
