### ISSUE TITLE
Allow extra options to the build process

### ISSUE THREAD

**Issue by braun1928** [terraform-aws-modules/terraform-aws-lambda#598]
Follow-up to #568 

## Is your request related to a problem? Please describe.
Originally issue was created due to a problem when building npm lambda with docker. Thinking this through, the workaround works, but can also make the process a bit clunky since it's different when building locally.

With `npm`, we might need to run `npm install --omit=dev`, with an alternative to add `NODE_ENV=production` environment variable in the `docker_additional_option`, but that doesn't handle the local build, which needs those variables set when running `terraform apply` (not tested).

Other runtimes might have the same issue, like `golang` using `GOOS` and `GOARCH` for instance, maybe `GOFLAGS` to add `-tags`, `-ldflags` (usually those are in arguments, so need to check if the env var is enough).

## Describe the solution you'd like.
Allow some variables to be exposed both for the docker build and local build.

## Describe alternatives you've considered.
Workaround only tested with the docker build, but with a local build it won't work.

**Comment by JulianYachelini** [comment]
I have the same problem.

**Comment by JulianYachelini** [comment]
this work for me

```
source_path = [
  {
    path = var.lambda_functions[count.index].source_path
    commands = [
      "npm install",
      "npm run build",
      "npm prune --omit=dev",
      ":zip"
    ]
  }
  ]
```
