### ISSUE TITLE
Added the "skip_destroy" argument for the "function" resource

### ISSUE THREAD

**Issue by catrielg** [terraform-aws-modules/terraform-aws-lambda#601]
✅: [AWS Lambda Function](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#argument-reference) 

## PR:
https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/600

**Comment by antonbabenko** [comment]
Fixed in #600
