### ISSUE TITLE
aws_s3_bucket_notification

### ISSUE THREAD

**Issue by Arwiim** [terraform-aws-modules/terraform-aws-lambda#610]
Can you provide an example for s3 bucket notification in the lambda module?

```
  allowed_triggers = {
    EVENT1 = {
      principal  = "s3.amazonaws.com"
      source = ?
    }
  }
  ```
  
  i have this resource for example, how should i attach to the lambda module for the allowed_triggers?
  
  ```
  resource "aws_s3_bucket_notification" "bucket_notification" {
  bucket = var.s3_datalake_raw

  lambda_function {
    lambda_function_arn = module.lambda.lambda_function_arn
    events              = ["s3:ObjectCreated:*"]
    filter_prefix       = "naranja/"
  }
}
```

**Comment by antonbabenko** [comment]
Hi @Arwiim !

Here is what you need - https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/tree/master/examples/notification
