### ISSUE TITLE
AWS lambda not redeploying with image with same tag changes

### ISSUE THREAD

**Issue by royassis** [terraform-aws-modules/terraform-aws-lambda#611]
## Description

When using the **AWS Lambda Terraform module** to build and deploy a lambda function.
After running terraform after the first time. If using the same image tag the image gets push to ECR
but the lambda is not updating. 

I don't know it this is by design or a bug, or customizable altogether.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
7.7.1 

- Terraform version: 1.9.3

- Provider version(s):
```
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.63.1
+ provider registry.terraform.io/hashicorp/external v2.3.3
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/kreuzwerker/docker v3.0.2
```

## Reproduction Code [Required]

```python
resource "aws_ecr_repository" "repo" {
  name = var.ecr-repo-name
}

locals {
  lambda_dir_path = "${path.module}/../../functions/validation_function"
}

locals {
  lambda_dir_checksum = sha1(join("", [
    for f in fileset(local.lambda_dir_path, "*") : filesha1("${local.lambda_dir_path}/${f}")
  ]))
}

module "docker_image" {
  source = "terraform-aws-modules/lambda/aws//modules/docker-build"

  ecr_repo      = aws_ecr_repository.repo.name
  keep_remotely = true
  use_image_tag = true
  image_tag     = var.image_tag
  triggers      = tomap({ lambda_dir_checksum = local.lambda_dir_checksum })
  source_path   = local.lambda_dir_path
}


module "lambda_function_container_image" {
  source                = "terraform-aws-modules/lambda/aws"
  function_name         = var.function-name
  create_package        = false
  image_uri             = module.docker_image.image_uri
  package_type          = "Image"
  memory_size           = 512
  attach_network_policy = false
  timeout               = 60
  build_in_docker       = true
  docker_file           = "${path.module}/../../functions/validation_function/Dockerfile"
  publish = false
  allowed_triggers = {
    OneRule = {
      principal  = "events.amazonaws.com"
      source_arn = aws_cloudwatch_event_rule.restore-testing-event.arn
    }
  }
  attach_policy_jsons = true
  attach_policy_json  = true
  #   environment_variables = jsondecode(var.env-variables)
  policy_json = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "Statement1",
        "Effect" : "Allow",
        "Action" : "s3:GetObject",
        "Resource" : "arn:aws:s3:::awsbackup-restore-test*/*"
      },
      {
        "Sid" : "Statement2",
        "Effect" : "Allow",
        "Action" : "s3:ListBucket",
        "Resource" : "arn:aws:s3:::awsbackup-restore-test*"
      },
      {
        "Sid" : "Statement3",
        "Effect" : "Allow",
        "Action" : "backup:DescribeRestoreJob",
        "Resource" : "*"
      },
      {
        "Sid" : "Statement4",
        "Effect" : "Allow",
        "Action" : "backup:PutRestoreValidationResult",
        "Resource" : "*"
      }
    ]
  })
}


module "alias_refresh" {
  source        = "terraform-aws-modules/lambda/aws//modules/alias"
  refresh_alias = true
  name          = "current-with-refresh"

  function_name    = module.lambda_function_container_image.lambda_function_name
  function_version = module.lambda_function_container_image.lambda_function_version

  allowed_triggers = {
    OneRule = {
      principal  = "events.amazonaws.com"
      source_arn = aws_cloudwatch_event_rule.restore-testing-event.arn
    }
  }
}

module "deploy" {
  source = "terraform-aws-modules/lambda/aws//modules/deploy"

  alias_name    = module.alias_refresh.lambda_alias_name
  function_name = module.lambda_function_container_image.lambda_function_name
  target_version = module.lambda_function_container_image.lambda_function_version

  create_app = true
  app_name   = "my-awesome-app"

  create_deployment_group = true
  deployment_group_name   = "something"

  create_deployment          = true
  run_deployment             = true
  wait_deployment_completion = true

}
```

## Expected behavior

Terraform updates the image with the same tag and updates the lambda

## Actual behavior

Terraform updates the image with the same tag but not updates the lambda

## Additional context

I am using workspaces in terraform cloud, the execution mode is local.

**Comment by antonbabenko** [comment]
To redeploy an existing Lambda function, you need to change the `image_uri` (e.g. make use of Docker tags). I don't think of any solution like [`replace_triggered_by`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) can work.

**Comment by ManushGupta** [comment]
@royassis I had the same issue and spent a lot of time to figure this out. So far what has worked for me

```
image_uri      = "${module.docker_image.image_uri}@${module.docker_image.image_id}"
```

while keeping use_image_tag equal to false in the docker_image module works for me. 

@antonbabenko The example for container images is misleading as it claims that if use_image_tag is set to false, it will automatically add the image digest to the image_uri, except that it throws an error while updating the lambda because it doesn't point to any specific image within the repo when keeping the tag false.

**Comment by royassis** [comment]
My goal was ultimatly to add a **latest** tag to the newest image + tag it with a unique version (e.g. v1, v2 etc.).
Also, I wanted to have a **current** lambda alias that points to the newest lambda version.

Can it be done?

**Comment by ManushGupta** [comment]
@royassis I haven't tried this myself but I believe you can actually add whatever tag you would like in the docker_image module. However when referencing the image_uri in the lambda, you would need to refer to the image digest for it to be auto deployed when a new image is pushed to ECR. 
Haven't used Aliases yet.
