### ISSUE TITLE
Allow users to ignore changes to image_uri. 

### ISSUE THREAD

**Issue by rohitjha941** [terraform-aws-modules/terraform-aws-lambda#614]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅

## Is your request related to a problem? Please describe.
I want to be about to ignore changes in `image_uri`. 

## Describe the solution you'd like.
Setting `ignore_source_code_hash`  to true adds a lifecycle rule which ignore changes in  `image_uri`

## Describe alternatives you've considered.
Using resources directly

**Comment by faizan-planview** [comment]
Aah need this really bad for my current project.
Just due to this I am being forced to create resources instead of using module :(
Can this be actioned sooner?
