### ISSUE TITLE
Kafka event source config missing

### ISSUE THREAD

**Issue by sergiolc** [terraform-aws-modules/terraform-aws-lambda#618]
## Is your request related to a problem? Please describe.
Somehow yes, we should be able to use the same configuration available to lambda versions in lambda alias and kafka event source config is missing for alias.

## Describe the solution you'd like.
PR https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/617

**Comment by sergiolc** [comment]
Any progress here?

**Comment by antonbabenko** [comment]
Fixed in #617. Thank you for the PR!
