### ISSUE TITLE
Logging configuration - changing type from text to json is not reflected in module

### ISSUE THREAD

**Issue by oleksandrsv** [terraform-aws-modules/terraform-aws-lambda#627]
## Description

After changing Log format from Text to JSON, module is not triggering any drift.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 4.18

- Terraform version:
Terraform v1.5.1
on darwin_arm64

- Provider version(s):
+ provider registry.terraform.io/hashicorp/archive v2.6.0
+ provider registry.terraform.io/hashicorp/aws v5.70.0
+ provider registry.terraform.io/hashicorp/external v2.3.4
+ provider registry.terraform.io/hashicorp/local v2.5.2
+ provider registry.terraform.io/hashicorp/null v3.2.3

## Reproduction Code [Required]

```
module "lambda_function" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 4.0"
```

Python code lambda:
```
# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
```

Deploy lambda.
Edit in AWS web console Logging configuration Log format Text -> JSON.

## Expected behavior

Some drift for logging configuration.

## Actual behavior

No changes.

### Terminal Output Screenshot(s)

<img width="1202" alt="Screenshot 2024-10-09 at 13 10 01" src="https://github.com/user-attachments/assets/04c03adb-5828-4ede-907b-f6fa2dc51e9f">

**Comment by antonbabenko** [comment]
Please make sure that you use version 7.0 of this module or newer.

Also, make sure that you provide these arguments in your configuration:
https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/examples/complete/main.tf#L436-L439
