### ISSUE TITLE
How to attach my own role to lambda

### ISSUE THREAD

**Issue by zillahchen** [terraform-aws-modules/terraform-aws-lambda#67]
I have set `create_role = false` and `lambda_role = my_own_lambda_role`. I know I can attach policies but is it possible to use my own role and not use the default created roles.

**Comment by antonbabenko** [comment]
This should be enough:

```
create_role = false
lambda_role = "your_lambda_arn_goes_here"
```

Please show the complete code you have if the problem persists.

**Comment by zillahchen** [comment]
perfect does what I expect 👍  thank you!
