### ISSUE TITLE
Allow the module to use terraform-provider-random v3

### ISSUE THREAD

**Issue by jecnua** [terraform-aws-modules/terraform-aws-lambda#70]
Hi all,

The random provider 3.0 is out now for more than a month.
At the moment is not possible for any state using this module, directly or inderectly via another module, to update to the new version.

This is the changelog: 
- https://github.com/hashicorp/terraform-provider-random/blob/master/CHANGELOG.md#300-october-09-2020

Since this module does not support terraform 0.11 or the b64 setting, I don't think the extension to support 3.x should be an issue.

**Comment by antonbabenko** [comment]
Good point.

[v1.28.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.28.0) has been just released.
