### ISSUE TITLE
Error module 'json' has no attribute 'load' comes from 'package.py'

### ISSUE THREAD

**Issue by babarbaig92** [terraform-aws-modules/terraform-aws-lambda#72]
Error: failed to execute "python3": Traceback (most recent call last):
  File ".terraform/modules/lambda/package.py", line 1246, in <module>
    main()
  File ".terraform/modules/lambda/package.py", line 1242, in main
    exit(args.command(args))
  File ".terraform/modules/lambda/package.py", line 1017, in prepare_command
    query_data = json.load(sys.stdin)
AttributeError: module 'json' has no attribute 'load'

Here is my python file 'destroy-infra.py'

import json

def lambda_handler(event, context):
    print("Hello")
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }

Here is my Terraform code 'main.tf'

provider "aws" {
  region  = "us-east-2"
  version = "~> 2.70.0"
  profile = "default"
}

module "lambda" {
  source        = "git@github.com:terraform-aws-modules/terraform-aws-lambda.git?ref=v1.27.0"
  publish       = true
  function_name = "destroy-infra"
  handler       = "destroy-infra.lambda_handler"
  runtime       = "python3.8"
  source_path   = ["destroy-infra.py"]
  hash_extra    = "hashstring"
}

The same code was working fine a day ago. But now it gives error.

**Comment by antonbabenko** [comment]
It looks like your Python installation is not complete (maybe you updated it lately?). Try checking section ["So what really happened?"](https://learnfromnoobs.com/python-attributeerror-module-json-has-no-attribute-loads/), it may help.

**Comment by babarbaig92** [comment]
Thanks, @antonbabenko for the quick response. I tried my code on a different machine and it was working fine. Looks like my current machine is having a problem with Python.
