### ISSUE TITLE
deploy - for default role, hook lambda names must begin with `CodeDeployHook_`

### ISSUE THREAD

**Issue by dominics** [terraform-aws-modules/terraform-aws-lambda#77]
Terraform version: 0.13.5
`deploy` module version: 1.30.0

I use a configuration where I leave `create_codedeploy_role` at its default `true`, and rely on the module creating the role for me (I don't specify any `codedeploy_role_name`). I also pass in an `before_allow_traffic_hook_arn`. (All are needed to reproduce this bug)

When I went to deploy, the created role didn't seem to have sufficient permissions. The error was:

```js
{
    "deploymentInfo": {
        // [...]
        "status": "Failed",
        "errorInformation": {
            "code": "IAM_ROLE_PERMISSIONS",
            "message": "The IAM role arn:aws:iam::123456789012:role/SomeLambda-codedeploy does not give you permission to perform operations in the following AWS service: AWSLambda. Contact your AWS administrator if you need help. If you are an AWS administrator, you can grant permissions to your users or groups by creating IAM policies."
        },
```

The role is present, and has the correct policies attached (including `AWSCodeDeployForLambda`). 

It turns out the above error is because I'm passing in a hook named `something_like_this`, and the managed policy expects hooks to conform to the ARN: `arn:aws:lambda:*:*:function:CodeDeployHook_*` - it might be nice to document this: for custom hooks, either name them beginning with `CodeDeployHook_`, or pass in custom role.

If we really want to be nice to end users, though, we could do better: if `var.before_allow_traffic_hook_arn` (or the "after" equivalent) is present _and_ `var.create_codedeploy_role` is set, invoke permissions could be included in the policy automatically.

**Comment by antonbabenko** [comment]
I think it would be enough if there is a note in the description of the variables for `after & before_allow_traffic_hook_arn` that function name should start with `CodeDeployHook_`. Also, if you have time, you can use [variables validation feature in Terraform](https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules) to make sure the provided value matches specified regex.

If necessary user can always pass the custom execution role.

Could you please update `deploy` example to show the end-to-end scenario?
