### ISSUE TITLE
Resource Policy Trigger doesn't work for API Gateway Custom Authorizers

### ISSUE THREAD

**Issue by cdhesse** [terraform-aws-modules/terraform-aws-lambda#78]
The code for lambda permissions checks to see if the service == apigateway, and if it does, it adds /*/*/* to the end of the value.  For lambda authorizers, this value needs to end in /authorizers/*.

**Comment by cdhesse** [comment]
My proposal is to simply take the passed in value when service == apigateway.  I can create a pull request which will work.  Should I do that?

**Comment by katya-tis** [comment]
I second that, I also stumbled on this issue a few days ago. Would be great if we can fix it!

**Comment by antonbabenko** [comment]
Good catch. I will now update it to use just `source_arn`, like this:

```hcl
source_arn = lookup(each.value, "source_arn", null)
```

**Comment by antonbabenko** [comment]
[v1.32.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v1.32.0) has been just released.
