### ISSUE TITLE
Lambda permissions

### ISSUE THREAD

**Issue by okuyiga** [terraform-aws-modules/terraform-aws-lambda#86]
TF: 0.14.2 
Module: 1.31.0

I'm running into an issue when I try to combine the `terraform-aws-lambda` module with an `aws_lb_target_group_attachment`. Is there an easy way to indicate to terraform that creation of the `aws_lb_target_group_attachment` depends on successful creation of the `aws_lambda_permission` resources created as part of this module?

**Comment by IaroslavR** [comment]
Look at `depends_on` meta-argument https://www.terraform.io/docs/configuration/meta-arguments/depends_on.html
