### ISSUE TITLE
source_path must be relative to where terraform is run

### ISSUE THREAD

**Issue by ers81239** [terraform-aws-modules/terraform-aws-lambda#89]
I created [this PR](https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/88) to better document and report errors based on how `source_path` is interpreted currently.

However, now I see that the current behavior is more of a problem than before.  I've created an `./examples/example1` dir for my module which has a `main.tf` that calls my custom module with a `source` of `../../`.  When I run `terraform plan` from within this examples directory, the `source_path` specified in the source is being interpreted relative to this `example1` directory instead of from the module's root directory.

This causes a `source_path must be set` error.

Recommended Fix:

Interpret `source_path`s relative to the location of the terraform file in which they are named.

**Comment by ers81239** [comment]
I was able to work around this by specifying source_path with "${path.module}/lambda_source_dir".  I still think my PR should be accepted.

**Comment by antonbabenko** [comment]
I have just merged your PR where documentation was updated.

Happy New Year!
