### ISSUE TITLE
Can't have multiple lambda_function_in_vpcs?

### ISSUE THREAD

**Issue by mannyveloso** [terraform-aws-modules/terraform-aws-lambda#96]
It looks like the modules don't support multiple instances of lambda_function_in_vpcs. Is that correct?

**Comment by antonbabenko** [comment]
Should work if you call this module multiple times and put different functions in different VPCs. Please show the code you are trying to run or the error message you see.

**Comment by mannyveloso** [comment]
Oh, I’m trying to put multiple functions in a VPC. I guess I’ll just go back to the old way.

**Comment by svenlito** [comment]
This works just fine.
