### ISSUE TITLE
Root resource was present, but now absent error

### ISSUE THREAD

**Issue by askaribragimov** [terraform-aws-modules/terraform-aws-lambda#98]
I make use of the module to create an AWS Lambda. I am changing the block as shown below: 

```
//WAS

  attach_policy = true
  policy        = aws_iam_policy.allow_ssm_read.arn
  
//NOW

attach_policies = true
  policies = [
    aws_iam_policy.allow_ssm_read.arn,
    "arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy"
  ]
  number_of_policies = 2

```

I am getting a behaviour, that when I run `terraform` first time, I get:
```
Error: Provider produced inconsistent result after apply

When applying changes to
module.<my-module>.module.lambda.aws_iam_role_policy_attachment.additional_many[0],
provider "registry.terraform.io/hashicorp/aws" produced an unexpected new
value: Root resource was present, but now absent.

```

However a second run added the SSM-related policy (that USED to be there initially) and no error is produced.

Is it something that can be improved so I do not get an error for the first run?

**Comment by antonbabenko** [comment]
Hi!

Please update the module version to the latest one ([v2.17.0](https://github.com/terraform-aws-modules/terraform-aws-lambda/releases/v2.17.0), see #195) where some improvements have been added to the way how IAM policies are attached to IAM role.

This should solve the issue you have experienced.
